### ISSUE TITLE
Button to re-scan library

### ISSUE THREAD

**Issue by WiWa** [timusus/Shuttle#1]
One of the only missing features in comparison to other local players is to purposefully re-scan the music library for newly added (or removed?) content.

**Comment by timusus** [comment]
This option is available via the folder browser (Shuttle+) to scan specific directories. In the past, the re-scan feature hasn't worked to well, which is why I removed it.

**Comment by WiWa** [comment]
Hmm, I remember in the past there was some bug with that, but it seems that this issue was fixed sometime. Seems to work fine without a scan button, sorry.
