### ISSUE TITLE
USB OTG Songs stuck in All Songs

### ISSUE THREAD

**Issue by cydia2020** [timusus/Shuttle#110]
**Shuttle version:**
 
 v1.6.7
 
**Device, OS:**
 
Google Pixel XL, PureNexusProject Android 7.1.2 r27
Build Version: NJH47D
Kernel: 3.18.60-PureKernel

**Description of bug:**

When plug in a OTG drive with audio files in it, Shuttle will scan that drive, but songs are stuck in the Shuttle "all songs" and "album" tabs afterwards
 
**Steps to reproduce:**
 
 1. Insert a OTG Drive
 2. Wait for sometimes
 3. Open Shuttle and find the songs stucked
 
**Expected outcome:**
 
Songs should be removed from tabs immediately after the removal of USB Drives
 
**Observations/Actual Result:**
 
Songs doesn't remove unless clear data

**Comment by timusus** [comment]
This is an issue with the MediaStore database on the device, rather than Shuttle itself.

You can read more about it in the [Shuttle FAQ](https://www.shuttlemusicplayer.com/#faq).
