### ISSUE TITLE
Mention that Shuttle is open source 

### ISSUE THREAD

**Issue by mirdaki** [timusus/Shuttle#112]
Hey, thanks for the awesome app. I switched to it full time a few months ago and have been very happy with it! I wanted to request that you mention Shuttle being open source on the website, in the app, and/or the app description. It helps someone like me who prefers using open source apps be able to see it is one (instead of randomly seeing a reddit thread about it like I did). Thanks again!

**Comment by timusus** [comment]
Thanks for the recommendation, I've updated the website and the store description :)

**Comment by mirdaki** [comment]
Thank you!
