### ISSUE TITLE
unable to build project in android studio,, can anyone provide me a full builded project in android studio (ZIP File)

### ISSUE THREAD

**Issue by adarsh2k** [timusus/Shuttle#114]
**Shuttle version:**
 
 v1.x.x
 
**Device, OS:**
 
Device info here

**Description of bug:**
 
Bug description here
 
**Steps to reproduce:**
 
 1. Step 1
 2. Step 2
 3. Step 3
 
**Expected outcome:**
 
Expected outcome here
 
**Observations/Actual Result:**
 
 Observations here

**Comment by timusus** [comment]
Please describe the issue using the issue template, rather than just the title. 

Cloning the app is the same as a 'builded zip file'.
