### ISSUE TITLE
Incorrect behavior when opening music file via external File Manager.

### ISSUE THREAD

**Issue by BezMan** [timusus/Shuttle#120]
**Shuttle version:**
 
 v2.0.0
 
Bug description here

opening music file thru external File Manager, opens another instance of the app, does not display clicked song file data (fields are blank on bottom drawer-fragment), opening bottom drawer-fragment simply shows prev opened song. app continues playing music of prev opened song.
 
**Steps to reproduce:**
 
 1. start music play ,selected within the app.
 2. open external file manager and select a music file to play.
 3. notice all the mentioned issues.
 
**Expected outcome:**
 
replace-recreate the activity/task. start play of selected song and display it's data.

**Comment by timusus** [comment]
I think this is due to some accidentally-removed code, which you can find in `MainActivity` on the `master` branch. 

Specifically:

https://github.com/timusus/Shuttle/blob/master/app/src/main/java/com/simplecity/amp_library/ui/activities/MainActivity.java#L997-L1032

**Comment by BezMan** [comment]
my latest pull request should be a good fix.
