### ISSUE TITLE
Drawer is locked - can't open nav drawer

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#125]
**Shuttle version:**
 
 v2.0.0-beta1
 
**Device, OS:**
 
Unknown

**Description of bug:**

After navigating (somewhere) in the app, and returning to the library, the hamburger menu stops working, and the drawer can't be slid out.
 
**Steps to reproduce:**
 
Unknown
 
**Expected outcome:**

Drawer should not be locked if hamburger menu is visile
 
**Other:**
There is a `DrawerLockManager` in Shuttle controlling the state of the nav drawer. Most likely, this is getting into the locked state somehow... Just need to find steps to reproduce the issue.

**Comment by timusus** [comment]
If anyone is experiencing this issue, it would be great if you can pause music, swipe away the notification, and then clear Shuttle from 'recents'.. Reopen the app, and describe the steps required to make this bug occur again.

**Comment by larcshectar** [comment]
Steps i followed to reporduce this bug (after a clean install) :
1.Went to settings from nav drawer
2.Changed default page to albums
3.enabled all the tab items
4.disabled Use Colors from artwork
5.Changed Accent and Theme Colour respectively.
6.Closed settings and switched to albums page.
6.Restarted the app after clearing it from recents.
7.Nav Drawer is now locked!

**Comment by timusus** [comment]
@larcshectar thank you for these detailed steps. The issue is the 'folder browser' being added to the main tabs. Will fix shortly.

**Comment by larcshectar** [comment]
This is the only issue preventing me from using it as daily driver...hope
it is fixed in next update. thank you! ☺
