### ISSUE TITLE
Artist detail screen - no default for song sort

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#130]
**Shuttle version:**
 
 v2.0.0-beta1
 
**Device, OS:**
 
Nexus 6P, others

**Description of bug:**
 
When opening the artist detail screen, songs are sorted by some unknown order, rather than 'default'.

**Comment by allenr85** [comment]
It can be noted that the default now seems to be sorting every song by track number, regardless if it's within a different album. This can be changed by selecting sort by album where it shows in the order pre-2.0 beta, but as with bug #131, this order is ignored when tapping an album to play the track.
