### ISSUE TITLE
Play/pause out of sync in notification bar

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#151]
**Shuttle version:**
 
 v2.0.0-beta
 
**Device, OS:**
 
MIUI9, Android N
Nexus 6P, Android O

**Description of bug:**

User report:

>Notification Player doesn't reflect whenever music was pause (pause/play icon)

**Comment by larcshectar** [comment]
This Is what I did
1.Play a song
2. Add 10-15 songs to que
3.Wait for 5-10 songs to complete with screen turned off.(not sure if I had shuttle in recents)
4.and the bug appears
I tried it only once as I did not get time

**Comment by timusus** [comment]
@larcshectar are you still able to reproduce this issue in the latest build(s)

**Comment by larcshectar** [comment]
will look into it soon(tonight or tomorrow)

**Comment by Zitrusfrucht** [comment]
I found a way to reproduce it on my device:
Oneplus 3T, OxygenOS 4.5.0, Android 7.1.1

0. No playback and shuttle not open in background
1. Press play on shuttle widget.

What happens:
After pressing play music starts and the play button on the widget transforms into a pause button. Also the shuttle notification appears, but the button is the play button.
This button still works but doesn't update to the correct icon.
