### ISSUE TITLE
Cleaning up / modernising the codebase

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#16]
I'd like to start using dependency injection, mostly just to get an understanding of how to use it. There's plenty more RX-ifying to be done as well.

I'll start spawning some tickets to cover specific details including:

- Reworking the old and crappy theming engine

- Not reusing layout resources (need to use includes a bit more)

- More to come..

**Comment by deletescape** [comment]
If there are things to be done about simply cleaning up existing code and having a second pair of eyes look over it I think I can be helpful :joy:

**Comment by Farmerjoe12** [comment]
Standing by to see what kind of ideas you have in mind.

**Comment by deletescape** [comment]
> Reworking the old and crappy theming engine

Instead of creating our own theming engine, it would probably be easier to use a theming library like for example [colorful](https://github.com/garretyoder/Colorful)

**Comment by timusus** [comment]
@deletescape definitely happy to move out to a 3rd party library. Shuttle's theming engine is very old and not particularly well written. It is also riddled throughout the app.

I guess I'll need to have a look at what's available and make sure it's capable of covering all the bases.

Are there any other suggestions, besides 'Colorful'?

**Comment by deletescape** [comment]
> Are there any other suggestions, besides 'Colorful'?

The only thing I've found with a quick search which looked kind of useful is another library by the same dev called [Android Theme Engine](https://github.com/garretyoder/app-theme-engine) doesn't really look like he's still working on it though.

I had a quick look into how Colorful works and tried to add it to Shuttle during that process I've realized that its feature set is probably way too small to fit Shuttle:

* There is NO way to define our own color values apart from the predefined ones.
* There is no fully black theme
* Only the primary and accent color can be changed

**Comment by timusus** [comment]
@deletescape I don't know if you're interested, but I've been slowly converting sections of the app to the MVP pattern. If you're interested, I could really use some help. There's so much to be done.

**Comment by deletescape** [comment]
@timusus I am definetly interested, but I am not sure if I can find any time right now as I've got a lot of other work to do, but I will jump in and try to help whenever I find some time :)

**Comment by timusus** [comment]
This is partially resolved, but always going to be an ongoing issue. There's nothing specific that needs to change, so I'm closing this issue.
