### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#17]
This is a catch-all ticket for UI improvements. I'll spawn tickets for specific details.

Ideally, UI changes can be discussed here (or in the child tickets), so we can share screenshots and discuss.

I've already started on some fairly major UI redesigns, which I'll publish on separate branches, and describe here later on.

**Comment by icarapovic** [comment]
Hi there! Im a developer but I had a fair amount of UI/UX/design experiance as I was working tightly with a design team on a couple of projects. I would be more than glad to help you with this and contribute. I can make mockups based on ideas to quickly evaluate changes before we would start any work on them. I know how to work in Sketch and Adobe Illustrator.

Besides that, I also started working on my own media player (open source ofc) with the goal to finally make an app for myself by myself. I was also thinking to make a lot of things that you mentioned that you would like to do, so we could share and learn from each other. Only thing that my app is still in very early stages.

Let me know when you push UI branches! :)

**Comment by timusus** [comment]
OK, #36 has been spawned to cover one of the UI improvements currently underway.

@icarapovic definitely keen for some help/feedback!

**Comment by Justin00015** [comment]
Could there be a feature that changes the color of the "up next" section based off of the album art's colors?
