### ISSUE TITLE
Songs order

### ISSUE THREAD

**Issue by rfazi** [timusus/Shuttle#176]
**Description of bug:**
 
When click play in the overflow menu for a folder, the song in that folder is played in the same order every time ignoring the user imposed order.
 
**Steps to reproduce:**
 
 1. Change order files for a folder, for example in order of filename.
 2. Click play in the overflow menu for a folder.
 3. The list doesn't respect the user imposed order.

Otherwise if the user have shuffle mode activated, the list can be shuffled. No?

**Comment by timusus** [comment]
This is the intended behaviour. To play songs in the listed order, you click on the first song. To play songs in the default order, you press 'play' from the overflow menu. 

Shuffle is another thing altogether, and should probably be discussed separately.
