### ISSUE TITLE
Delay in artist and album closing animation

### ISSUE THREAD

**Issue by balzabalza** [timusus/Shuttle#180]
**Shuttle version:**
 
 2.0.0 betas; this doesn't occur on 1.6.7 (I tested it on my borther's Huawei).
 
**Device, OS:**
 
Nexus 5x, OnePlus 3T

**Description of bug:**
 
As stated in this [Google Plus post](https://plus.google.com/111215731694086537622/posts/HU2EzZhjM1p?fscid=z13bzjor5sblxri3222fuzrgirqrivx4j04.1504526422361196), the artist and album closing animations are a bit "lazy": once the back button is pressed, I have to wait 1 or 2 seconds before getting to the main page. Moreover, the artist/album cover animation to the original position is not smooth, since the image doesn't move at all, but it disappears (and then it is reloaded in the main page). Opening is fine, only closing is a bit messy.

Finally, if the same artist or album page is opened for a second time, the closing animation is visible, and delay seems to be shorter.
 
**Steps to reproduce:**
 
 1. Open artist or album page from main tab menu. Animation is smooth
 2. Close artist or album page with the back button. Animation is broken, delay is expected
 3. Open again artist or album page from main tab menu. Animation is smooth
4. Close again artist or album page. Animation is smoother, but not perfect, and delay is shorter
5. Once Shuttle is opened again, the same bug is present

**Comment by timusus** [comment]
Thanks. I've been working on this the last few days. Should be fixed in the next beta.

**Comment by balzabalza** [comment]
Yeah. I can't believe how fast you're going!
