### ISSUE TITLE
Nav drawer header placeholder not showing

### ISSUE THREAD

**Issue by cocobelgica** [timusus/Shuttle#186]
**Shuttle version:**
 
 v2.0.0-beta11 (free)
 
**Device, OS:**
 
Android 7.1.2

**Description of bug:**
 
Not exactly a bug per se - currently when no song is playing the header of the navigation drawer where the album cover is displayed(during playback) is left blank/empty. How about just clearing/removing the header and bumping up the nav drawer items a la Phonograph instead of an empty header. Screenshot below for reference.

![screenshot](https://i.imgur.com/dEB6vWY.jpg)

**Comment by timusus** [comment]
Ah OK, it's meant to be displaying a placeholder image there, will fix.
