### ISSUE TITLE
Music doesnt resume/notification gone after long call

### ISSUE THREAD

**Issue by IOI-655321** [timusus/Shuttle#194]
**Shuttle version:**
 
 v2.0.0 beta 12
 
**Device, OS:**
 
Nexus 5X Oreo (Sept update)

**Description of bug:**
 
On latest beta (and previous ones) I've noticed recently after a period of going back to Google Play Music (GPM) that the lock screen notification for GPM remains indefinitely (while app open) if you are on a call or pause or some such and music auto starts again if the call drops or ends.  With Shuttle it disappears after a while and if this happens the music doesn't auto start playing again after the call.  
 
**Steps to reproduce:**
 
 1. Listen to music
 2. Take a phone call of reasonable length
 3. After call drops/ends lockscreen notification is gone and music doesnt auto play
 
**Expected outcome:**
 
Expected music to resume or at least have notification available to start playing.
 
**Observations/Actual Result:**
 
No notification or music playing after call.

**Comment by BigNickBurgess** [comment]
Is this likely to be fixed with the Exoplayer changes coming down the line? Been a while since it was logged and it is an annoying bug.

**Comment by timusus** [comment]
Should be resolved with v2.0.6. Will reopen if not.

**Comment by IOI-655321** [comment]
This is still an issue.
