### ISSUE TITLE
Supported lyric formats / file extensions

### ISSUE THREAD

**Issue by firewater2** [timusus/Shuttle#200]
What tag is supported for lyrics? I have all my songs with <lyrics>, but it doesn't seem to pick them up.

**Comment by timusus** [comment]
Lyrics are supported via the `TEXT` field of mp3 id3v2.4 tags. I believe lyrics are supported for older versions of id3.

I'm not sure about other file formats, my only advice is if it doesn't show up (and check Shuttle's built in tag-editor to be sure), then that file format is not supported.

**Comment by firewater2** [comment]
Oh, is `TEXT` standard? I mean that I use `LYRICS`, since I thought it was the most common used tag for storing lyrics. And I use mp3s exclusively, yeah.
