### ISSUE TITLE
Oreo support

### ISSUE THREAD

**Issue by mople71** [timusus/Shuttle#207]
**Shuttle version:**
 
 latest
 
**Device, OS:**
 
Nexus 5X, Android 8.0

**Description of bug:**
 
Persistent notifications don't work. Shows just app is running in background.
 
**Steps to reproduce:**
 
 1. Open Shuttle
 2. Play a song
 3. Exit Shuttle
 
**Expected outcome:**
 
Notification with music controls should appear.
 
**Observations/Actual Result:**
 
 System notification that Shuttle is running in background.

**Comment by timusus** [comment]
This is resolved in the current beta.
