### ISSUE TITLE
Weird issues regarding unicode characters handling

### ISSUE THREAD

**Issue by peczony** [timusus/Shuttle#208]
**Shuttle version:**
 
 v2.0.0-beta12 (but the last stable Google Play issue also has this bug)
 
**Device, OS:**
 
Oneplus 3T, Oxygen OS 4.5.1

**Description of bug:**
 
Sometimes the characters displayed on screen don’t match the characters present in file tags. Opening the ‘Edit tags’ menu reveals the correct characters
 
**Steps to reproduce:**
 
Start playback of certain files. Weird characters or question marks are displayed instead of actual characters. Here is an Imgur post with screenshots: https://imgur.com/a/E1bef
 
**Expected outcome:**
 
The same, correct characters should be displayed in Edit Tags menu and other places of the app.
 
**Observations/Actual Result:**
 
Correct characters are displayed only in Edit Tags menu.

**Comment by timusus** [comment]
This is an issue with the Android MediaStore, hence why you're seeing it in other apps as well. It looks like it's incorrectly parsing the characters from the tags.

I don't have any advice for you sorry. Shuttle currently relies on the MediaStore, and that's not working correctly, which is an issue for Google.
