### ISSUE TITLE
Toggle between 'current play time' and 'remaining time'.

### ISSUE THREAD

**Issue by raindropsfromsky** [timusus/Shuttle#213]
**Shuttle version:**
  v2.0.0. beta 12
 
**Device, OS:**
OnePlus 3T
OxygenOS 4.5.1 (Android 7.1.1)

**Description of bug:**
The "Play controls" panel shows the scroll bar (line, actually), below which it shows the "currently playing time" (left) and "total play time" (right).

But Shuttle does not display the remaining time for the current track.

Sometimes the user is interested in checking this (e.g. if he is listening to a lecture instead of music while he is commuting, and he wants to check whether the lecture will finish before he reaches.)

It would be nice to be able to toggle the display between "current time" and "remaining time", by tapping on the same place

**Comment by timusus** [comment]
This is resolved and available in v2.0.0-beta(19+?)
