### ISSUE TITLE
In search results, the songs should have an overflow menu that is similar to album's conext menu.

### ISSUE THREAD

**Issue by raindropsfromsky** [timusus/Shuttle#216]
**Shuttle version:**
v2.0.0. beta 12

**Device, OS:**
OnePlus 3T
OxygenOS 4.5.1 (Android 7.1.1)

**Description of bug:**
 In the search results, the Albums have multiple options in the overflow menu (three vertical dots): Play, Add to... > , Edit tags, Biography, blacklist, delete.

But the songs in the same list have no options at all, except to change the search filter settings (yes/no option for fuzzy, artists, albums).

**Desired:**
The filter settings should not be associated with songs. The panel should have these controls. They should be common between folders and songs.

**Comment by timusus** [comment]
Fixed with #43a91e40
