### ISSUE TITLE
Allow user to select multiple songs from the search results and add them to playlist/queue

### ISSUE THREAD

**Issue by raindropsfromsky** [timusus/Shuttle#217]
**Shuttle version:**
v2.0.0. beta 12

**Device, OS:**
OnePlus 3T
OxygenOS 4.5.1 (Android 7.1.1)

**Bug description here**
I ~should~ would like to be able to select multiple songs from the search results and add them to the queue or playlist. This is a common use scenario.

~Please provide this option.~

**Comment by timusus** [comment]
Closed in favour of #154
