### ISSUE TITLE
Album View filter to hide albums with only a few songs.

### ISSUE THREAD

**Issue by BellerophonM** [timusus/Shuttle#236]
**Shuttle version:**
 
1.6.7
 
**Device, OS:**
 
Xperia Z5, Android 7

**Feature Request:**

Album view can often be confused because I have a lot of single songs which have their full ID3 info including original album, so album browser is full of junk. If I'm in the mood to play a full album of songs, it's hard to sort my actual albums from the one-off songs. A filter on this view to hide all albums with less than three or four songs would be appreciated.

**Comment by Lenbok** [comment]
Duplicate of #115?

**Comment by timusus** [comment]
Yep. Closing in favour of #115
