### ISSUE TITLE
Feature: Beep when song is changed via headset button

### ISSUE THREAD

**Issue by faho** [timusus/Shuttle#24]
One feature from Vanilla Music I really like is the option to beep when I change songs via double-pressing my headset's button.

The reason for this is that, with songs often starting with a few seconds of silence or fade-in, it's difficult to tell if I've paused or skipped.

Since both applications are GPLv3, you might be able to crib parts of their implementation - see https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/MediaButtonReceiver.java.

**Comment by timusus** [comment]
I think this is a great idea. Obviously needs to be optional though. I'd use this myself.
