### ISSUE TITLE
a Proposal for new logo

### ISSUE THREAD

**Issue by orelmely** [timusus/Shuttle#250]
https://steemit.com/utopian-io/@orelmely/contribution-new-logo-for-shuttle-music-player-open-source-vector-format

**Comment by timusus** [comment]
Thanks for your contribution.

Personally I'm not a fan of this logo. 

It doesn't follow Google's iconography principles for mobile apps, particularly with the square gradient background.

The colours look kind of retro, but aren't really in line with Shuttle's branding at all. It doesn't invoke any sense of modernity.. I think this would really make Shuttle look its age.

It looks like you have ability, but I don't think much effort went into this one. The Steemit page looks like a giant ad. and you've just copy-pasted the logo at ridiculous proportions onto a bunch of play store/website screenshots. 

I think you can do better!
