### ISSUE TITLE
Folder Navigation Suggestion

### ISSUE THREAD

**Issue by akanealw** [timusus/Shuttle#264]
I use the folder navigation almost exclusively for viewing, sorting, and playing music. I have the home folder set to my Music folder in my internal SD. However, when I press back from the home folder it takes me out of the Music folder and up to the parent directory until it gets to the top then closes the app. 

Suggestion: Give an option to lock navigation to the selected home folder. Personally, I have no need to go up to a parent directory when at the root of home folder. When the root of the home folder is reached, give an option to exit the app and stop playing music or exit the app and keep playing music with a setting for the default selection.

Thanks!

**Comment by adneal** [comment]
@akanealw I thought this was a good suggestion, so keep an eye out for it in the next beta/update.
