### ISSUE TITLE
Download album art for all albums at once

### ISSUE THREAD

**Issue by firewater2** [timusus/Shuttle#265]
It seems there's no option to do this. The "download artwork" on my end seems to only be triggered once the album art is requested - be it by playing the song, or browsing it on the "Up Next" menu. I only have Internet at my home and a large library of songs, so often I find myself with empty covers when I go out.

**Comment by timusus** [comment]
Settings -> Artwork -> Download Artwork

**Comment by firewater2** [comment]
I tried that plenty of times before submitting this issue, and it just didn't work for me. I would get a notification about downloading artwork, with a loading bar that would take ages to finish, that also didn't seem to download anything until I actually went into the song. I tried this by letting it sit there hours loading up the bar (which I would assume means "downloading a lot of artwork"), then turning off Wi-Fi and playing some songs. None of them had covers.

In fact I just went on a trip and, though the covers were there when playing with Wi-Fi, during my trip (without internet), none of them had covers.
