### ISSUE TITLE
Doubled/Tripled artists or albums and all caps artists text styling

### ISSUE THREAD

**Issue by enricocid** [timusus/Shuttle#266]
**Shuttle version:**
 
 v2.0.2
 
**Device, OS:**
 
Xiaomi Mi A1, Android 8.0.0

**Description of bug:**
 
About doubled/tripled albums/artists:

 Sometimes I get doubled/tripled albums and doubled artits. I don't know if this is the case, but if You use ArrayList to collect data why don't You try to pass the resulting list to an HashSet before returning it?

For example, if I have an ArrayList to remove duplicates I do the following to remove them:

ArrayList values=new ArrayList();
(Add things to values)

HashSet hashSet = new HashSet();
hashSet.addAll(values);
values.clear();
values.addAll(hashSet);

This happened to me when querying for example for contacts and this is how I solve. HashSet is very useful to avoid duplicates in lists.

About all caps (not important): 

I know it depends by tags, but it would be awesome if you can improve text styling. 
Looking at the screenshot below KREATOR should be styled to Kreator :)

 
**Screenshots:**

![screenshot_20180109-092425](https://user-images.githubusercontent.com/7274841/34711705-a3ce47a6-f520-11e7-9fe7-8d2d868aae28.png)

![screenshot_20180109-092317](https://user-images.githubusercontent.com/7274841/34711707-a3f78f4e-f520-11e7-9d73-bb6f78f4eb77.png)

**Comment by timusus** [comment]
In response to the duplicates, have you tried rescanning/rebuilding your media library? A `HashSet` is not the solution here - Shuttle displays the results from the MediaStore. If you have two tracks which have identical data, there's no reason to hide that from the app.

If you're seeing multiple entries for one artist/album, check the tags of the underlying songs. Most likely, there is a mismatch in some of the fields i.e. for an album, the artist, album artist, genre, year, total discs, etc fields should all match for each track

If you're seeing duplicates and you believe your tags are correct, either these duplicates actually exist on your device, or you have a corrupt media store. For the latter, see https://www.shuttlemusicplayer.com/#faq.

The 'text styling' stuff should be moved to a separate issue.

**Comment by enricocid** [comment]
Yes, it is because they are different CDs. It would be awesome then if you do something to merge albums with the same name like in PowerAmp (that has problems in android 8 because it is not updated). I really like shuttle+ but this is a little bit annoying problem :)

**Comment by timusus** [comment]
Multi-disc albums are supported (and automatically merged) in Shuttle. I'd say you just need to clean up the id3 tags.

**Comment by enricocid** [comment]
I have solved artists list issue, it was due to artist album field not compiled for all albums.

Anyway, I have still problems with albums list. In this example, Arise does not have multiple CDs and the tags are the same. I have also tried to clear media store but the problem  persists :-\

![screenshot_20180109-112711](https://user-images.githubusercontent.com/7274841/34716521-638febf8-f530-11e7-9420-4fd11c628ae3.png)
![screenshot_20180109-112650](https://user-images.githubusercontent.com/7274841/34716522-63c065a8-f530-11e7-9fe4-a79ff714736c.png)

**Comment by timusus** [comment]
I'm not sure what's happening there, the tags do appear to be the same. Can you upload those two tracks here, so I can try them on my device?

**Comment by enricocid** [comment]
The only difference is that the two songs are placed in different folders. If I move these files in the same folder I can solve the problem. But I can't because I have a folder with the songs I have to listen and a folder with the songs I decided to keep because promoted.
Can You make something to merge songs from the same album but from different folders?

**Comment by timusus** [comment]
Ah, I see. This is another problem with the MediaStore. Because the files are contained in different folders, they are treated differently, and given different album & artist IDs. 

If work around the problem, then songs that don't belong together will end up being merged.

This is a problem you can solve with folder management - it's going to take much less work for you to change your folder structure than for me to write a workaround in code.
