### ISSUE TITLE
Unable to remove songs from queue

### ISSUE THREAD

**Issue by balzabalza** [timusus/Shuttle#269]
**Shuttle version:**
 
 v2.0
 
**Device, OS:**
 
Nexus 5X, Oreo 8.1
**Description of bug:**
 
I'm unable to use the trash icon to remove songs from queue. The icon I'm referring about is the one in the upper right corner of this screenshot:
![screenshot_20180111-104001](https://user-images.githubusercontent.com/26390194/34819566-57f99c50-f6be-11e7-8ba1-2b145b8c4acd.png)
 
**Steps to reproduce:**
 
 1. Step 1 Open queue, and select some songs to be removed
 2. Step 2 Tap the trash icon
 3. Step 3 Nothing happens
 
**Expected outcome:**
 
Songs should be removed from queue

**Comment by lastbulletbender** [comment]
I think the expected outcome is to delete the song. It started after this commit https://github.com/timusus/Shuttle/commit/a2aa1868a3f8f4066cde8ab2dedfbe4648466b99. The `newInstance()` in `DeleteDialog.java` gets an empty list of songs from the calling function.

**Comment by adneal** [comment]
This should be fixed in beta-4+.
