### ISSUE TITLE
Back press handled incorrectly when 'folders' is displayed in main tabs

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#270]
**Shuttle version:**
 
 v2.0.2+
 
**Device, OS:**
 
Any

**Description of bug:**
 
When the folder browser is displayed as one of the main tabs (settings -> display -> ...) it seems to intercept back press events and swallow them, even when it's not the currently selected tab, preventing the app from exiting regularly.

See video:
https://streamable.com/dm1am

**Comment by lastbulletbender** [comment]
What behaviour is expected in the other tabs? I ask this because on my phone it takes a total of 5 presses to close the app from all tabs.
