### ISSUE TITLE
While choose the tab menu & select any of three or less then three it will be show wired so better then you make autofit it will be set automataclly.

### ISSUE THREAD

**Issue by rahuljnext** [timusus/Shuttle#272]
**Shuttle version:**
 
 v1.x.x
 
**Device, OS:**
 
Device info here

**Description of bug:**
 
Bug description here
 
**Steps to reproduce:**
 
 1. Step 1
 2. Step 2
 3. Step 3
 
**Expected outcome:**
 
Expected outcome here
 
**Observations/Actual Result:**
 
 Observations here

**Comment by timusus** [comment]
Please update the title to something which briefly describes the issue, and then fill out the issue template.
