### ISSUE TITLE
Music keeps playing during phone calls

### ISSUE THREAD

**Issue by TriceB** [timusus/Shuttle#281]
**Shuttle version:**
 
 v2.0.3
 
**Device, OS:**
 
LG V30 - Android 7.1.2

**Description of bug:**
 
With the latest update, every time I receive a call or make an outgoing call, the music no longer pauses. It keeps playing during the call, so the other person and I can't hear one another. I have to manually pause the music for the call, then manually press play again after the call is over (as it doesn't start back up after the call like it used to either).

 It happens on both regular calls just using the phone itself and also when I have a Bluetooth headset or car audio connected.

Just this past Tuesday morning, I hadn't played any music on my phone since Sunday. Tuesday, I made a call and once the phone started ringing, the last song I was playing, on Sunday, started up again playing through the phone speaker (no Bluetooth connected). 

I don't use any other music app on my phone. The Play Music app is disabled and this does not happen with the default LG music player (this app has not been opened in months). 
3 scenarios below
- I listen to music in Shuttle and receive a call or make a new call and the music just keeps playing instead of pausing like it usually does. 
- I listen to music in Shuttle then manually pause when I need to make an outgoing call but the music starts back up once the phone starts ringing. 
--Neither of those times does the music start playing again after the call issue over as it normally does. I always have to manually press play again. (This could be because the manual pause is a hard pause, so typically if no music has been playing - no music will start back up after the call)
-Or there's no music playing at all, I make a call or receive a call, and music starts playing along with the call or while the phone is ringing.

**Steps to reproduce:**

(1) When listening to Music 
 1. Listen to Music in Shuttle
 2. Receive a phone call or make a phone

(2) When Listening to Music 
1. Listen to Music in Shuttle
2. Manually pause music
3. Make a phone call

(3) When no music is playing 
1. No music is playing
2. Receive a phone call or make a phone call

(4) After phone call
1. End phone call
 
**Expected outcome:**
 
(1) Music should pause when receiving a phone call or when you make an outgoing call.
(2) After manually pausing in order to make a call - Music should remain paused during the phone call.
(3) As there is no music playing prior to the outgoing call or the incoming call - no music should begin playing once the call starts
If music was playing prior to call
(4) After the call has ended, the music should begin playing again (Shuttle usually does this automatically)
 
**Observations/Actual Result:**
 
(1) Music does not pause when receiving a phone call or when you make an outgoing call - music continues playing until it is manually paused (causing neither party to be able to hear)
(2) Music does not remain paused. Once the phone begins to ring, the music starts playing again.
(3) Music starts playing the last song previously played once the phone call is answered (incoming) or once the phone starts ringing (outgoing)
If music was playing prior to call
(4) After the call has ended, music does not begin playing - I have to manually press play to start the music again.

**Comment by TriceB** [comment]
Adding to the above, yesterday on Jan 30, 2018, I was listening to music using Shuttle on Bluetooth headphones and received a phone call. The call interrupted the music briefly (like a quick second just for the phone to show there was a call coming in) then when the phone started ringing, both the music and the phone ringer were going at the same. Before I could push the button to answer, the person calling hung up (the call ended) then the music paused. It is odd that it paused after the call rather than before.

**Comment by timusus** [comment]
Thanks for the detailed report. We will look into this.

**Comment by timusus** [comment]
I haven't been able to reproduce this issue, and I've had no other reports of the same issue occurring. I'm putting it down to a device/firmware bug.
