### ISSUE TITLE
Swiping through albums of an artist doesn't work half the time. 

### ISSUE THREAD

**Issue by Coaltrainman** [timusus/Shuttle#284]
**Shuttle version:**
 
2.0.3
 
**Device, OS:**
 
Samsung s7, 7.0

**Description of bug:**
 
Trying to swipe through an artists albums that has many doesn't work well. Have to swipe repeatedly to make it move. 
 
**Steps to reproduce:**
 
Go to an artoay with many albums
Try to swipe left through the albums
 
**Expected outcome:**
 
It would swipe through the albums 
**Observations/Actual Result:**
 I need to swipe many times before it will actually work.

**Comment by timusus** [comment]
I'm able to reproduce this on my 6P running Android 8.1. This may be related to #192

**Comment by timusus** [comment]
Closing in favour of #192
