### ISSUE TITLE
Cannot remove songs from playlists

### ISSUE THREAD

**Issue by Jmoney1997** [timusus/Shuttle#285]
**Shuttle version:**
2.0.3
 
**Device, OS:**
 
Motorola Moto x Pure, 7.0

**Description of bug:**
 
Cannot remove songs from playlists using the remove button. Blacklisting the songs doesn't work either, the songs show up as blacklisted but are still in the playlist.

My music is also on a SD card if that helps.
 
**Steps to reproduce:**
 
1. Open playlist
2. Open the 3 dot options menu for an individual song in the play list
3. Select remove
4. nothing happens almost as if I didn't press the button
 
**Expected outcome:**
 
The song would be removed from the playlist.
 
**Observations/Actual Result:**
 
The songs do not disappear from the playlist. From all appearances nothing happens when I hit remove on a song.

**Comment by RobertKajnak** [comment]
Same conditions, pressing "Play next" removes the song instead. "Remove" does nothing.
I'm pretty sure it worked in the previous version as I used the feature frequently.

Shuttle version: 2.0.3.
Device: Galaxy A5 (2017) SM-A520F

**Comment by adneal** [comment]
This should be fixed in the latest beta.
