### ISSUE TITLE
Support lyricswiki?

### ISSUE THREAD

**Issue by Ufeldraku** [timusus/Shuttle#286]
As title says, would using lyricswiki for lyric download/display be possible?

Having to download another app, and put more stuff into RAM isn't really good for a 2GB phone...

Also, QuickLyric doesn't really work properly as of now, and with lyricswiki support, it could look nice in the app.

**Comment by adneal** [comment]
Unfortunately no. Too much of a legal thing. The best alternative at the moment is to use a third party program to fetch them for you and then embed them in your ID3 tags. Depending on your library size you could also copy/paste them from somewhere and edit the tags yourself in Shuttle. Hopefully in the future though!

**Comment by Ufeldraku** [comment]
Oh, Retro does it so I thought it was ok, but, ok.

**Comment by adneal** [comment]
Retro is playing with fire. I think natively displaying lyrics would be awesome, but unless we come up with a way to do it that separates that feature from the rest of the app, then we're just putting Shuttle at risk to get taken off the Play Store.

**Comment by Ufeldraku** [comment]
Uh, didn't know it.
