### ISSUE TITLE
"Play next" removes song from playlist or does nothing

### ISSUE THREAD

**Issue by RobertKajnak** [timusus/Shuttle#287]
**Shuttle version:**
 
 v2.0.3 (Free)
 
**Device, OS:**

Android 7.0
Galaxy A5 (2017) SM-A520F

**Description of bug:**
 
Pressing "Play next" removes the song from the playlist and does not add it to the queue. It doesn't matter if it is a generated playlist, like "Recently added" or a playlist file. If it is removed from a generated list, it is added back the next time the playlist is opened; this is not true for playlist files (.m3u in my case).

"Play next" still works as intended if used from "Songs" tab. If t searching for a song from the search bar, it only works on the songs section, not the other sections described below.

If used from "Suggested", "Genres", "Artists", "Albums", the song is neither deleted nor added to the queue and the toast does not appear either. 

If the Add to... > Queue is used, the toast "1 song added to queue" appears, but has no actual effect, regardless from where it is used. 
 
**Steps to reproduce:**
 
 1. Open playlist
 2. Tap the 3 dots
 3 Select "Play next"
The rest is described above
 
**Expected outcome:**
 
Both the toast appearing and song being added to the queue
 
**Observations/Actual Result:**
 
Worked last version (or forelast, I'm not sure when I updated it last time)
I can add a screen capture tomorrow if necessary.

**Comment by timusus** [comment]
Related to #285

**Comment by RobertKajnak** [comment]
Checked, and It's working fine in V2.0.2-release. (Both the play next and the remove song)
The Add to...>Queue is still not, but I'm not sure if that is intended to have the same functionality or not. The toast message is the same, so I would assume so

**Comment by JesseMillward** [comment]
I'm experiencing this in the version from the Play Store.

**Comment by adneal** [comment]
This should be fixed in the latest beta.
