### ISSUE TITLE
Albums "Year unknown" but "Edit tags" shows the right year.

### ISSUE THREAD

**Issue by AlexanderOMara** [timusus/Shuttle#289]
**Shuttle version:**
 
 v2.0.3
 
**Device, OS:**
 
Nexus 6P, Android 7.1.2

**Description of bug:**
 
In the album list under the artist view, all of my albums say `Year unknown`. However, when I click on `Edit tags` for the individual songs, I can see see the `Year` field is set correctly to a 4-digit year (ie. `2007`).
 
**Steps to reproduce:**
 
 1. Tap Artists
 2. Tap an artist card
 3. See `Year unknown` under all of them
 
**Expected outcome:**
 
Expected to see the year I guess and be able to sort by them correctly.
 
**Observations/Actual Result:**
 
Instead I see `Year unknown` under all the albums.

I think this is also the reason I have not been able to get the albums to sort by year correctly for the past few versions.

**Comment by atriede** [comment]
I have the same issue.

I use Picard to tag my files on PC and I believe the date is set to dd-mm-yyyy, at least when available.

Shuttle can understand that in the tag editor (or just the year) but in the interface it shows 'Year unknown'.

Hope this will help for fixing this issue.

**Comment by timusus** [comment]
The problem is (as per usual) with the MediaStore.. It's not great at parsing the year value from the tags, and seems to fail with various filetypes and date configurations.

I don't really have a good solution to this at the moment, hopefully eventually if we ever complete #13

**Comment by atriede** [comment]
Understood. However, considering the tag editor correctly identifies the year, is there any way to pull that value at least in the mean time?

**Comment by AlexanderOMara** [comment]
Also, if there is a date and/or filetype configuration known to work, that would be nice to know.

**Comment by GeoZac** [comment]
Can the issue be related to the year being parsed as  integer ,as all my files have just the year and they are showing up perfectly

**Comment by timusus** [comment]
@AlexanderOMara since it seems to depend on file type as well as tag format, I'm not really aware of a working configuration. I'll have a look into it.

@GeoZac reading tags is really slow and inefficient - otherwise I would show the year from the tags. If there was a simple way to do this, there would be no need for #13.

I'm thinking about writing a settings option which will iterate over the tags and update the MediaStore, I'll let you know how it goes.

**Comment by baloe** [comment]
having the same issue with ogg-vorbis files

**Comment by baloe** [comment]
@timusus this issue needs to be reopened in my opinion or should I create a new one? I still encounter this bug in version 2.0.11, though it only affects ogg-vorbis files.
