### ISSUE TITLE
Support MediaSession queue access

### ISSUE THREAD

**Issue by Maxr1998** [timusus/Shuttle#29]
Supply the queue to [`MediaSessionCompat.setQueue()`](https://developer.android.com/reference/android/support/v4/media/session/MediaSessionCompat.html#setQueue(java.util.List<android.support.v4.media.session.MediaSessionCompat.QueueItem>)) to allow accessing the queue from e.g. [my XMediaNotificationTrackSelector module](https://github.com/Maxr1998/XMediaNotificationTrackSelector).

**Comment by timusus** [comment]
This is also required for / part of #19

**Comment by Maxr1998** [comment]
Thanks, looking forward to this!

**Comment by timusus** [comment]
Depends on #244

**Comment by timusus** [comment]
Closed with v2.0.5-beta5
