### ISSUE TITLE
Add "Play Next" to Artists, Albums, etc

### ISSUE THREAD

**Issue by Kaisonic** [timusus/Shuttle#297]
**Shuttle version:**
 
 v2.0.3 (free)
 
**Device, OS:**
 
Moto Z Force Droid Android 7.1.1

**Description of bug:**
 
(Enhancement request) Please add a "Play Next" option to groups of songs, like Artists, Albums, Genres, etc. This action would have the same effect as Add to -> Queue, except the songs would go after the current song rather than the end of the queue.

**Comment by adneal** [comment]
This will be available in the next beta/update!

**Comment by GeoZac** [comment]
@adneal Seems you missed a spot on the Artist/Album Detail Screen or was this intended?

**Comment by adneal** [comment]
@GeoZac What spot do you mean exactly? Did you pull from the latest `dev` branch to verify that? The artist/album detail screens have the option in all the popup and CAB menus for me, as far as I can tell.

**Comment by GeoZac** [comment]
The  screen which is called when we tap an Album/Artist from main activity. I found the menu in question was menu_sort_detail and called in the Basedetailfragment.java

**Comment by adneal** [comment]
@GeoZac Ah, good call. Just fixed it.

**Comment by GeoZac** [comment]
I was reluctant to add that many new functions, thanks for the quick fix

**Comment by adneal** [comment]
@GeoZac Don't let that stop you, break away. :)
