### ISSUE TITLE
With a dark substratum theme, the now playing notification is unreadable.

### ISSUE THREAD

**Issue by that1communist** [timusus/Shuttle#30]
Title pretty much says everything, i'm using 7.1.1, I don't really think logs are necessary as its easily testable.

Just play a song, look at the notification, while using a dark substratum theme.

A simple tickbox that asks whether or not you're using a dark theme would fix this, but i'm sure there are other, better ways to auto-detect.

**Comment by faho** [comment]
Have you checked the preferences? There is one that says "Invert notification" in display settings. That might do what you want.

**Comment by timusus** [comment]
I don't think explicitly asking the user whether their notification theme is dark or light is a very good approach from a UX perspective. 

As @faho says, there is an option to invert the notification controls in settings. 

Unless you know of a clever way to detect the background colour of someone's notifications, I don't see a better solution than what's already available in the app.

**Comment by that1communist** [comment]
@faho I swear I triple checked for that option, I somehow missed it.

I do not know of a better solution, thank you, I apologize.

**Comment by timusus** [comment]
No worries :)
