### ISSUE TITLE
"Play Next" option when choosing from Artist/Album/Genre no longer working.

### ISSUE THREAD

**Issue by Shinibana** [timusus/Shuttle#300]
**Shuttle version:**
 v2.0.3 (upgraded)
 
**Device, OS:**
 Android 6.0.1
 Oxygen 3.6.1 

**Device Model:**
 One Plus 2

**Description of bug:**
 "Play Next" option when choosing from Artist/Album/Genre no longer working.
 Is working when choosing from "Up Next" Queue or "Songs" tab.
 
**Steps to reproduce:**
 1. Start playing a Genre or Album (Shuffled or otherwise)
 2. Select a song - "Play Next" from Artist, Album or Genre
 3. Nothing occurs
  
**Expected outcome:**
 Song would enter the queue as the next one to play
 
**Observations/Actual Result:**
 Nothing Occurs:
  No message indicating song is queued
  Track does not enter queue at next or any position

**Notes**
 Before last update this produced the expected outcome with no issue
 Phone has been rebooted, Shuttle+ Cache/Data Cleared, App Uninstalled/Reinstalled

**Comment by GeoZac** [comment]
Please do check reported issues before posting a new one.

**Comment by adneal** [comment]
This should be fixed in the next beta/update.
