### ISSUE TITLE
Choose directories for scanning media

### ISSUE THREAD

**Issue by gergesh** [timusus/Shuttle#303]
I'd love an option that'll allow me to select which directories are white/blacklisted for media scanning.  
**Expected outcome:**
 Have an option to select which directories are included in the library.
**Observations/Actual Result:**
 Audio files such as /sdcard/random_app/not_music.mp3 appear in my library, forcing me to blacklist them one at a time.

**Comment by GeoZac** [comment]
The Blacklist and the Whitelist feature (Settings > White/Blacklist) serves the same purpose as you suggested.

**Comment by gergesh** [comment]
They most definitely can, but there should be a way of blacklisting a whole
folder at once and not just per-song. Maybe it's possible for paid users
but not for the rest.

**Comment by timusus** [comment]
Blacklisting/whitelisting folders is available via the folder browser (paid version)
