### ISSUE TITLE
Can i use this code and modify and publish, any liccence issue on this ?

### ISSUE THREAD

**Issue by anoopputhukkudy** [timusus/Shuttle#308]
**Shuttle version:**
 
 v1.x.x
 
**Device, OS:**
 
Device info here

**Description of bug:**
 
Bug description here
 
**Steps to reproduce:**
 
 1. Step 1
 2. Step 2
 3. Step 3
 
**Expected outcome:**
 
Expected outcome here
 
**Observations/Actual Result:**
 
 Observations here

**Comment by timusus** [comment]
License information can be found here:
https://github.com/timusus/Shuttle/blob/dev/LICENSE.md
