### ISSUE TITLE
Controls are off screen in landscape

### ISSUE THREAD

**Issue by Bluerobot1234** [timusus/Shuttle#309]
**Shuttle version: 2.0.4 Beta 3**
 
 
**Device, OS:**
Android 8.0, OnePlus 3T, OxygenOS 5.0.2

**Description of bug:**
 Controls go slightly off screen in landscape
 
**Steps to reproduce:**
 
 1. Play music
 2. Open now playing
 3. Turn device to landscape and observe
 
**Expected outcome:**
Controls should be inline with UI and easy to see/press
 
**Observations/Actual Result:**
Controls are slightly off screen creating an eyesore and making it difficult to press

**Comment by timusus** [comment]
I'm able to reproduce this on my Nexus 6P running Android 8.1.0

**Comment by Entity447B** [comment]
I'm seeing this on my Moto G4 Plus as well.
