### ISSUE TITLE
Suddenly can't play songs/library empty

### ISSUE THREAD

**Issue by tofkop** [timusus/Shuttle#314]
**Shuttle version:**
 
 v2.0.3
 
**Device, OS:**
 
Galaxy s7 edge, android 7.0

**Description of bug:**
 
Suddenly music not showing up in library. When browsing to folders all songs appear as unkown - unknown.mp3. In file explorer they appear normal. Can open and play the files in vlc without issues. Trying to open the song from a filebrowser only opens shuttle without anything appearing in the player/no músic playing.
Already restarted the phone, uninstalled and reinstalled app with no luck.

**Steps to reproduce:**
 Don't know for sure what happened. I was trying to set it as default music player so ok Google would use it as default. Checked in shuttle's settings and set it to open links with shuttle instead of browser. 
Going to see if I figure it out, and will update if I find something.

 
**Expected outcome:**
 
N/A
 
**Observations/Actual Result:**

N/A

**Comment by tofkop** [comment]
Already found out that the filenames appear when I select that option.

**Comment by tofkop** [comment]
When I browse to an mp3 in the shuttle file browser and select it to play it, I get a toast message saying that the specified list outs empty and to add a song to it by clicking on a song - add to playlist. 
I also tried to open an aac file with the same results.

**Comment by tofkop** [comment]
It could be the codification? It's 15 songs that I downloaded using a 'convert from youtube' site, the only thing is I thought I could play them before this error. Im including 2 screenshots and one of the files if it can help you? 
And there's no .nomedia-file and didn't use the white/blacklist option.
Also, when browsing to them using Shuttle+ I cant get the file-info - I do when using vlc.

http://iefdelvo.be/bugreport.7z - 2 screenshots & one mp3file.

**Comment by timusus** [comment]
Can you try using the 'scan' option in the folder browser to scan the files? 

I suspect that the problem is the files aren't present in the MediaStore. You can confirm this by checking whether the songs show up in the other sections of the app (outside of the folder browser).

**Comment by tofkop** [comment]
Hi timusus, sorry for the late reply.
The Reagan option didn't fix it, but im 99% sure you are right about media storage. I noticed that in the default my gallery app pictures that are stored on my internal memory aren't showing up neither. 

Force deleting the media storage cache and data and rebooting didn't fix it. I. Running an app called media re.scan atm, didn't fix it neither. I'm sure there 're no .nomedia files in the folders as well. I'll update if I find it out if you want, but im sure it's not a shuttle related bug.

**Comment by tofkop** [comment]
Welp, apparently I made a .nomedia file in the root of my internal memory....
Deleting that, updating media storage fixed it. 

Didn't think to check the rootfolder for a .nomedia file because my pictures appeared in the piktures app, only saw it when I opened the native gallery app.

Thx for the support!
