### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [timusus/Shuttle#317]
Greetings, I'm a graphic designer and I would love to contribute to your project with a logo. This is completely free, take it as a contribution (which you can accept or not). In case you agree I would be presenting sketches and you will be choosing/modifying the aspects you like more so we could work on the perfect logo for your project together.

Let me know what do you think?, best regards. :)

**Comment by timusus** [comment]
Sure, that would be great.

Since this will likely involve a lot of discussion, I recommend you join slack:
http://shuttle-slack-inviter.herokuapp.com/
