### ISSUE TITLE
Artist Name Sorting

### ISSUE THREAD

**Issue by Comeonpilgrim** [timusus/Shuttle#327]
**Shuttle version:**
 v2.0.4
 
**Device, OS:**
Pixel XL (1st gen)
Android 8.1.0

**Description of bug:**
Sort by Artist Name doesn't always sort correctly if the Artist Name begins with "The". It also sorts by Firstname instead of Lastname.
 
**Steps to reproduce:**
 1. Set Library View to Albums
 2. Set Sorting to Artist Name
 
**Expected outcome:**
It should sort alphabetically by Artist Name. It should not sort Artist Names that begin with "The" under "T". It should sort Artist Name by Lastname and then Firstname.
 
**Observations/Actual Result:**
It's sorting "The Black Angels" under "T" and "Wanda Jackson" under "W". In the MP3/ID3 tags I have the "Sort As For Album Artist" and "Sort As For Artist" set to "Black Angels" and "Jackson, Wanda" respectively. Those are just two examples but all artists with "The" in the name are under "T" and all artists that have Firstname Lastname are sorting Firstname only.

**Comment by timusus** [comment]
Shuttle ignores leading words such as 'the' and 'a' when sorting artists - if the sorting is set to 'default'. If you change sorting to 'artist name', then sorting occurs alphabetically by the first character.

> It should not sort Artist Names that begin with "The" under "T"
By default, it doesn't.

> It should sort Artist Name by Lastname and then Firstname.
I don't agree with this. What is the 'last name' of 'At The Drive In', 'Beyonce', or 'The Spice Girls'?

Shuttle does not support 'sort as' id3 tags, and cannot differentiate between first and last name.

**Comment by Comeonpilgrim** [comment]
It would be great then if if either supported the "sort as" ID3 tags or used the same logic to ignore leading words in all sorting views, not just default. I just want to be able to browse my tracks the same way I do when they're on the shelf at home, grouped by artist and then by album.
