### ISSUE TITLE
Podcasts show up in normal library

### ISSUE THREAD

**Issue by CharoSW** [timusus/Shuttle#329]
**Shuttle version:**
 
 v2.0.4
 
**Device, OS:**
 
Android 8.0.0, Sony Xperia

**Description of bug:**
 
Podcasts in the Podcasts directory show up in the normal library when they should probably just be confined to their spcialised playlist.  They show up in the shuffle lists because of this. 
 
**Steps to reproduce:**
 
 1. Copy files the the Podcasts dir of your storage
 2. check that they pop up in the Podcasts playlist to signal Shuttle is reading them as Podcasts
 
**Expected outcome:**

 They don't appear in the normal library
 
**Observations/Actual Result:**
 
 They appear in the main library tabs and thus can be shuffled

**Comment by timusus** [comment]
I agree that podcasts don't need to show up outside of the podcast playlist.
