### ISSUE TITLE
i will love to do copywriting for you 

### ISSUE THREAD

**Issue by Hamzeto938** [timusus/Shuttle#335]
I love your application and would want to contribute to it, I'm not a developer but I am good at copywriting. I would love to make a copywrite for your Readme and make a pull request for you to merge. Your response would be highly appreciated. Also I would like to request if we could communicate via email, so I don't have to create issues. Thank you.

**Comment by timusus** [comment]
Thanks for your enquiry. I'm not sure copywriting is something that's really lacking or needed for Shuttle. But, if you'd like to make a pull request I'd happily look at it.

You can chat via Slack if you like, the link is on the readme. Otherwise, opening issues/PRs is probably the best approach.
