### ISSUE TITLE
Unable to set default folder 

### ISSUE THREAD

**Issue by the-vindicar** [timusus/Shuttle#338]
**Shuttle version:**
Shuttle+ v2.0.4, Russian translation.
 
**Device, OS:**
Samsung Galaxy S3 Neo GT-I9301i
Cyanogenmod 12.1, build of 2017-11-26 (based on Android 5.1.1)

**Description of bug:**
Unable to set a folder as a default music folder. There is simply no such action neither in folder context menu, nor in Shuttle+ settings screen.
 
**Steps to reproduce:**
Open Folders page.
Go to the folder, containing the would-be initial folder.
Press context menu button (three dots) next to desired initial folder name.

**Expected outcome:**
There is a "Set as initial directory" item in the context menu.

**Observations/Actual Result:**
There are following items in the context menu (back-translated): 
* Play
* Play next
* Add to... >
* Scan
* Whitelist
* Blacklist
* Rename
* Delete from disk

**Comment by the-vindicar** [comment]
Apologies. In my defense, the meaning of that icon is not entirely clear without any text - it looks much like "new folder" icon.

**Comment by timusus** [comment]
That's fair, although you can long-press to view the icon's description, which is 'set home directory'.
