### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by TJBlack31** [timusus/Shuttle#340]
**Shuttle version:**
 
Shuttle+ v2.0.4
 
**Device, OS:**
 
Samsung Galaxy Edge S7

**Description of bug:**
 
Code will not compile in Android Studio with this error:

    File google-services.json is missing. The Google Services Plugin cannot function without it. 
     Searched Location: 
    /Users/Morticia/Shuttle/app/src/amazon/free/release/google-services.json
    /Users/Morticia/Shuttle/app/src/amazonFree/release/google-services.json
    /Users/Morticia/Shuttle/app/src/release/amazonFree/google-services.json
    /Users/Morticia/Shuttle/app/src/amazon/release/google-services.json
    /Users/Morticia/Shuttle/app/src/amazon/free/google-services.json
    /Users/Morticia/Shuttle/app/src/amazon/freeRelease/google-services.json
    /Users/Morticia/Shuttle/app/src/amazonFree/google-services.json
    /Users/Morticia/Shuttle/app/src/release/google-services.json
    /Users/Morticia/Shuttle/app/src/amazonFreeRelease/google-services.json
    /Users/Morticia/Shuttle/app/src/amazon/google-services.json
    /Users/Morticia/Shuttle/app/src/amazonRelease/google-services.json
    /Users/Morticia/Shuttle/app/google-services.json

 
**Steps to reproduce:**
 
1.  Cloned Repo and during Gradle build, error surfaced
 
**Expected outcome:**
 google-services.json should be present
 
**Observations/Actual Result:**
 
google-services.json is not present.

Thanks!
-TJB

**Comment by GeoZac** [comment]
Build **DevDebug**  variant as it is the default configuration. Other variants requires additional keys and configs.

**Comment by timusus** [comment]
Please see [Contributing](https://github.com/timusus/Shuttle/blob/dev/.github/CONTRIBUTING.md) for help on getting started.

**Comment by ArthurMartin2** [comment]
If I cannot use Release variant then how will i publish an app on Google play?

**Comment by timusus** [comment]
You're going to need your own API keys and Google Services json file to build a release build.

**Comment by ArthurMartin2** [comment]
I'm new to programming. I have a keystore using which I have signed an app before to publish on Google play. What API keys I need and where I have to put them? And where can I get google-services.json?

**Comment by ArthurMartin2** [comment]
Can you please tell me an open source music player for Android to get started?

**Comment by timusus** [comment]
Yes, Shuttle is a good one to get started. Just use the development variant and you'll have a build on your phone in no time.

**Comment by ArthurMartin2** [comment]
Thanks. I installed it on my phone. But only devDebug version works.

**Comment by timusus** [comment]
That's all you need to get started. 

Look, Shuttle is open source, and you're allowed to use it however you like (within the bounds of the license).

The source code is here to help developers see how it works, improve it or create their own forks. It's not here for you to just clone, rename and publish as your own. 

If you're interested in development and you need help understanding the code, I'm here to help. If you're just looking to publish this and pretend that it's your own, you'll have to get help elsewhere.
