### ISSUE TITLE
Shuttle on Android P DP2 Does Not Read Tags

### ISSUE THREAD

**Issue by cydia2020** [timusus/Shuttle#342]
**Shuttle version:**
 
Shuttle Plus v2.0.5 beta2
 
**Device, OS:**
 
Google Pixel XL
Android-P Preview 2

**Description of bug:**
 
Song tag (artist, album) was not read, every tag reported as *null*
 
**Steps to reproduce:**
1. Upgrade to Android-P
2. Open Shuttle
3. Magic

 
**Expected outcome:**
Tag should be read
 
**Observations/Actual Result:**
 
Attempted to clear data and cache, but it still does not read tag.

**Comment by timusus** [comment]
Can you please describe the issue in more detail?

Where are the tags not read, on which screen? 

Are we talking about the actual id3/Vorbis tags, or are the song names just null in the song list screen (which comes from the MediaStore)

Some more informative steps to reproduce would be great as well.

**Comment by cydia2020** [comment]
G'day mate, thanks for replying

Initially, when I first upgraded to Android P a few hours ago and open Shuttle to listen to my collections later, everything was blank (nothing is on the display) except the top menu and the side slide menu
I tried to clear data and cache afterwards and thought it'd fix the problem, but when I open shuttle back up after clearing data, every tag was read as *null*

I don't have a screenshot for now as my Pixel XL is at home and I am at work.

Cheers

**Comment by timusus** [comment]
OK, so I don't think the 'tags' are read as null - Shuttle populates the artists/albums/songs/etc. from the MediaStore database. 'Tags' as in actual id3/Vorbis tags are read in by Android's MediaScanner.

It sounds to me like you need to rebuild your media library (MediaStore). Perhaps try going to the folder browser in Shuttle (paid version only), choose the root directory of your music, press the overflow button and then 'scan'.

**Comment by cydia2020** [comment]
Hey, good morning

I did try to rebuild the library, and as expected, it did work
Closing the issue now

Thank you

________________________________
差出人: Tim Malseed <notifications@github.com>
送信日r: Wednesday, May 9, 2018 5:46:17 PM
宛先: timusus/Shuttle
CC: 池たくみ; Author
件名: Re: [timusus/Shuttle] Shuttle on Android P DP2 Does Not Read Tags (#342)


OK, so I don't think the 'tags' are read as null - Shuttle populates the artists/albums/songs/etc. from the MediaStore database. 'Tags' as in actual id3/Vorbis tags are read in by Android's MediaScanner.

It sounds to me like you need to rebuild your media library (MediaStore). Perhaps try going to the folder browser in Shuttle (paid version only), choose the root directory of your music, press the overflow button and then 'scan'.

―
