### ISSUE TITLE
Show total song time on queue, like on playlists

### ISSUE THREAD

**Issue by ajzett** [timusus/Shuttle#346]
**Shuttle version:**
 
 v2.0.5-beta2
 
**Device, OS:**
 
Moto G4, OmniROM 8.1.0

**Suggestion:**
 
Recently, in v2.0.5-beta1 of Shuttle, it was made possible to see how long a playlist was. This is a feature I had been hoping for for some time. However, most of the time, people make queues on the fly in lieu of playlists, and as such can't take advantage of this feature.

I suggest showing the time on your queue as well.

**Comment by timusus** [comment]
Resolved with 6cf26
