### ISSUE TITLE
Shuffle button remains white until pressed

### ISSUE THREAD

**Issue by Bluerobot1234** [timusus/Shuttle#355]
**Shuttle version:**
 
 v2.0.5-beta6
 
**OnePlus 3T, OxygenOS 5.0.3, Android 8.0**

**Description of bug:**
 
Shuffle button remains white until pressed making it difficult to see on white backgrounds
 
**Steps to reproduce:**
 
 1. Open Shuttle
 2. Play any track with white artwork
 3. Observe white shuffle button
 
**Expected outcome:**
 
The shuffle button should turn black with the rest of the UI elements
 
**Observations/Actual Result:**
 
 Shuffle button remains white while the other buttons change to black.

**Comment by michaelcerne** [comment]
+1

**Comment by jnpatel2811** [comment]
PR#382
