### ISSUE TITLE
Suggestion : Swipe to remove from queue

### ISSUE THREAD

**Issue by HavermansStef** [timusus/Shuttle#361]
**Shuttle version:**
 
 v 2.0.4 (Free)

**Device, OS:**

Huawei P9 Lite
EMUI 5.0.1
Android 7.0
 
**Suggestion**

When having the play next queue, it would be very useful to be able to have the possibility to remove a song from it by swiping it. This is implemented in multiple other music applications such as the GPM application. 

Keep up the good work and thumbs up to the dev(s). Love the application.

**Comment by timusus** [comment]
I agree. Shuttle used to have this feature, but it was a little too trigger happy, so people were accidentally swiping stuff away from the queue.

I think I'd like to implement this feature with a 'lock' icon in the toolbar, so you can lock/unlock the queue from swipe/rearrange actions. Probably unlocked by default.

**Comment by HavermansStef** [comment]
This would be the golden mean. I hope this could be implemented anywhere soon. I'm a developer myself and would always be happy to help if needed. Thanks for the reply.
