### ISSUE TITLE
Track orders in albums won't change

### ISSUE THREAD

**Issue by patjissa** [timusus/Shuttle#379]
v2.0.6 (upgraded)
 
HTC U11+, Android 8.0
 
When you tap any album, the order of the tracks are jumbled up and they aren't in ascending or descending order. 
You try to use the option at the top to order the tracks in ascending or dealing order but it won't work. It sticks to a certain order and you can't change it!!

Very annoying and can't enjoy an album in order from track 1 to end!

 
Bug description here
 
**Steps to reproduce:**
 
 1. Open any full album where tracks have track numbers
 2. Tap the option with the three lines (left of the three dot option section)
 3. Tap "Track #" and tap ascending. The ascending button changes nothing and/or they move around but don't completely fix.
 
**Expected outcome:**
 
Just for it to work properly, or keep it so that out of default tracks start from #1 to end in order only.
 
**Observations/Actual Result:**
 
 Cluttered result of track numbers and ascending bar never changes selection.

**Comment by IOI-655321** [comment]
Just as a quick check you've not got it in shuffle mode have you?

**Comment by patjissa** [comment]
Hey,
No it's the same thing whether it's in shuffle or not.
