### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by alanorth** [timusus/Shuttle#38]
Currently there is not much information on building this. It would be nice to have some basic information like Java version (7 or 8?) and Android SDK packages required. This would help new would-be contributors get started.

**Comment by timusus** [comment]
Fair enough.

In the meantime, Java 8 (Shuttle uses Retrolambda & Java 8 features). 

I'm currently using the latest canary build of Android Studio - once the next stable build comes out, I'll update the gradle version to stable, and I won't commit canary gradle versions to source control.

As for SDK packages, rely on Android Studio to tell you what you're missing (if anything).

**Comment by Farmerjoe12** [comment]
For some reason, I can't build and run shuttle with instant run enabled. Is anyone else having the same issue?

**Comment by icarapovic** [comment]
@Farmerjoe12 Instant run is (at the moment) not compatible with Jack compiler which is used for Java 8 features.

**Comment by amitkpandey** [comment]
When trying to build it is throwing Error:Execution failed for task ':app:processAmazonFreeReleaseGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\Shuttle\app\src\amazonFree\release\google-services.json
  D:\Shuttle\app\src\release\amazonFree\google-services.json
  D:\Shuttle\app\src\amazonFree\google-services.json
  D:\Shuttle\app\src\release\google-services.json
  D:\Shuttle\app\google-services.json

is anyone else facing the same issue?

**Comment by timusus** [comment]
@amitkpandey 

>make sure your build variant is devDebug

See the 'getting started' section of the [Contributing](https://github.com/timusus/Shuttle/blob/master/CONTRIBUTING.md) document.

**Comment by amitkpandey** [comment]
so i need to opt the devDebug build variant specifically.

**Comment by timusus** [comment]
@amitkpandey that's right.

**Comment by alanorth** [comment]
The `devDebug` variant is pretty annoying, though, as it constantly reports memory leaks and the like. Did I do something wrong or is this the only way to successfully build a "regular" version of Shuttle from source?

**Comment by timusus** [comment]
@alanorth I wouldn't call that 'annoying', that sounds more like 'working as intended'. It is a _debug_ variant.

You can turn `LeakCanary` off by using the `no-op` version of that library dependency in `dependencies.gradle`.

If by 'regular' version, you mean a release build (similar to what's on the Play Store), you'll need to switch to a release build variant, and then provide the required information for Gradle to build a release apk. This includes signing keys (a keystore and valid `keystore.properties` file), as well as a Last.FM API key.

Sample keystore.properties:

```
store=<path to keystore>
alias=<keystore alias>
pass=<pass>
storePass=<keystore pass>
```

I don't think a Crashlytics API key is required for building a release variant, but it may be. If it won't build without it, have a look at how it is disabled in the `devDebug` variant, and do the same for the `release` variant. I currently store these in `private.properties`. Which looks like this:

```
LASTFM_API_KEY=<Last.fm API key>
CRASHLYTICS_API_KEY=<Crashlyics API Key>
```

**Comment by alanorth** [comment]
Ah, yes. My annoyance was at the fact that the recommended build is the `devDebug` variant, not that the debug variant was doing debug things. 😄

I'm not very good with Android Studio and gradle, but other projects make it simple to build "regular" versions without much configuration ([Signal](https://github.com/WhisperSystems/Signal-Android), [vanilla music](https://github.com/vanilla-music/vanilla), [NetGuard](https://github.com/M66B/NetGuard), [ooni probe](https://github.com/TheTorProject/ooniprobe-android), [dns66](https://github.com/julian-klode/dns66), etc). I don't know how they do that.

**Comment by timusus** [comment]
All you need to do is clone the source, choose `devDebug` and hit run, and Android Studio will deploy a functional apk to your device. 

So it is simple to build Shuttle, and I think a debug variant is 'regular' enough for someone doing development work. 

Instead of asking me to modify the codebase so it builds to your requirements, why don't you try to build it yourself, and then explain which parts you're having trouble with?

**Comment by alanorth** [comment]
Here is a good example of how to add build instructions to an open-source software project without being hostile to users and treating open source like it's an afterthought or a marketing ploy.

https://github.com/tomahawk-player/tomahawk-android

**Comment by timusus** [comment]
That's a bit rough. These are different apps with different build requirements. I actually went to a lot of effort to make this project easy to build after its cloned. 

I'm not being hostile, I'm honestly offering to help you if you can tell me what your specific problems are. 

I'm not willing to make changes to the app just for your sake though. If the development variant builds properly for someone after cloning the project, I'm happy with that. 

There's no need for this to descend into mud slinging.

**Comment by BezMan** [comment]
[CONTRIBUTING.md is now here.
](https://github.com/BezMan/Shuttle/blob/dev/.github/CONTRIBUTING.md)
Must go to - Build Variants - window in Android Studio and change app's variant to - devDebug.

**Comment by BezMan** [comment]
There must be a way to open the project with the devDebug selected already as default. I'll check it out.

**Comment by timusus** [comment]
I did research this a while ago, I don't believe it's possible.

**Comment by timusus** [comment]
https://github.com/timusus/Shuttle/blob/master/CONTRIBUTING.md
