### ISSUE TITLE
Add FAQs

### ISSUE THREAD

**Issue by HarryHeights** [timusus/Shuttle#388]
Hi. I'm Harry. I'd like to create FAQs document for your project. I'm a content creator sort of and I like contributing to open source projects by creating documents which I think might be valuable. 
If it's okay by you, I create the doc right away.

**Comment by timusus** [comment]
Are you talking about an FAQ for the app, or for the repository?

Happy to chat about this on Slack or Discord:
http://shuttle-slack-inviter.herokuapp.com/
https://discord.gg/4Z5EU7K
