### ISSUE TITLE
[Bug] Chromecast doesn't connect

### ISSUE THREAD

**Issue by drjoe123** [timusus/Shuttle#389]
**Shuttle version:**
 
 Shuttle+ v2.07 beta 3
 
**Device, OS:**
 
Samsung Galaxy Tab S2 running Nougat 

**Description of bug:**
 
No response when clicking on chromecast icon. It doesn't connect to TV at all. 
 
**Steps to reproduce:**
 
 1. Before selecting music, hit icon, select Chromecast unit, Chromecast doesn't respond 
 2. After selecting song, hit icon, select Chromecast unit, Chromecast doesn't respond
 3. Tried two different Chromecast units (Living room, bed room) neither responds
4. Other apps connect to Chromecasts with no issues. 
 

Thanks for your help, 

Joe

**Comment by timusus** [comment]
Thanks for the report. I'm investigating this issue. In the meantime, could you check whether you have the latest Google Play Services installed?

**Comment by drjoe123** [comment]
> Thanks for the report. I'm investigating this issue. In the meantime, could you check whether you have the latest Google Play Services installed?
> 
> Also, when you say 'Chromecast doesn't respond'.. Are you getting the dialog to choose your Chromecast device? Does it show the device name (Family Room TV, or whatever)? Or is it just that absolutely nothing happens when you press the Chromecast button?

Google play services is current as far as I can tell. Ver. 14.33.66 {040306-213742215) Sept 25, 2018.

There's a beta version I can sign up for, but I'll wait for feedback from you. 

Joe

**Comment by timusus** [comment]
Thanks Joe.

I'm not suggesting this is a problem with anything other than Shuttle. I'm just trying to get to the bottom of the issue.

**Comment by drjoe123** [comment]
I didn't mean to imply you were trying to suggest otherwise - I'm impressed with your response and appreciate your time and effort. Let me know if there's anything I can do to help troubleshoot the issue. As I said, I'd be willing to try reverting from the beta to your fully released version if it would help. I installed the plus version and immediately enrolled in the beta. I was having an issue with another player - 90% of my songs disappeared and I needed to see if it was the other player, or if it was Android Media Storage. I gave your program a shot because of its Chromecast capability. Shuttle+ had the same missing songs, so I deleted the cache and several hours later that my songs reappeared. Now, I'd like to see how your player compares. Looks like it has some nice features. 

Thanks, 

Joe

**Comment by timusus** [comment]
No worries Joe.

The latest beta actually makes some sweeping changes to Chromecast, so there's a good chance the non-beta version will work correctly. But I wouldn't recommend switching back to the non-beta version.. I'll try and push out another update tonight which _may_ fix this issue.

Thanks for checking out Shuttle. If you're interested, there's a Discord channel where we can discuss things further:
https://discord.gg/4Z5EU7K

**Comment by drjoe123** [comment]
So I just tried casting CNN, and had the same behavior. Allcast, ESPN, Fox Sports Go also wouldn't cast, but VLC player and Google Home worked fine. I rebooted the tablet and now all seem to be are casting again. So this likely wasn't particular to Shuttle. I'm going to scratch my head and say it is working now. Not sure what is up, hasn't ever happened like this before. I casted ESPN and Fox Sports Go fine on Saturday (college football☺️). I'll let know if the problem recurs

**Comment by timusus** [comment]
Oh, that's interesting. A bit of a relief too, because I've just overhauled Chromecast. So while I'm expecting issues, I'm also hoping there are none that I can't reproduce!

I've just updated the Chromecast library from 15.0.1 -> 16.1.0. I'm not sure what changed on Google's end, but hopefully this will improve stability.
