### ISSUE TITLE
UI Improvements: Now Playing Screen

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#39]
See 8840755e Now playing UI changes: Initial commit

This is a work in progress, aimed to rework the Now Playing screen with a couple of changes:

The album art is now full-bleed to the top of the screen. A text protection scrim is used to make the contents of the toolbar visible.

The ‘up next’ queue is no longer shown via a FAB, but rather an additional sliding panel at the bottom of the screen.

Much of the work for this fairly major UI change has been undertaken in this commit, however, the landscape mode is completely nerfed. I’ve got some designs/ideas for how the now playing screen should look in landscape mode, but it’s quite different from portrait, so there’s a fair bit of work to be done. The unfinished landscape stuff is a pretty big hurdle for finalising this change.

There are still some bugs to iron out as well, including:

1.) The toolbar doesn’t always respond to the panel slide, sometimes it remains opaque when it should be transparent

2.) The queue seems to disappear, not exactly sure under what circumstances at the moment.

3.) Plenty of others I've forgotten.

Screenshots (portrait):

![1](https://cloud.githubusercontent.com/assets/4422616/23405650/5aa29144-fe0f-11e6-999a-7d3b2a2fc65b.png)
![2](https://cloud.githubusercontent.com/assets/4422616/23405656/5d1fb9ec-fe0f-11e6-8183-8d32b711ed6f.png)

Landscape Mockup:

![landscape](https://cloud.githubusercontent.com/assets/4422616/23405944/bb7b2a34-fe10-11e6-92d9-1731ffbec1ad.png)

**Comment by icarapovic** [comment]
Tip: Move the playback controls up and title and artist under it. They should ideally be at 1/3 height of the screen. 

Why?

Hold your phone as you would normally do. Try to click on the controls. If you struggle to reach down to the controls, this is bad UX. The controls should be at the height of your thumb for easy control. In order to click it, you should only need to move the thumb left or right, not up and down. 

Try it out and see how you feel about it.

**Comment by ShadyIIV** [comment]
Screenshot 2: 
1. Think it should have "up next" in there somewhere to make it clear what's up next.  
2. I would keep play controls on the screen. A user might like to stay on this view.
3. In the list: The song that is currently playing could use an indication that it's currently playing.

**Comment by Thaodan** [comment]
On Meego touching the cover showed up next.
I think the idea was that the media que is behind the cover.
I really liked that idea as it makes an extra 'up next' button redundant.

**Comment by timusus** [comment]
Done (on local branch, will be pushed before long).
