### ISSUE TITLE
[Feature request] Truly Random Next Track

### ISSUE THREAD

**Issue by backseatpilot** [timusus/Shuttle#400]
**Shuttle version:**
 
 v2.0.6
 
**Device, OS:**
 
Google Pixel 3, Android Version 9

**Description of request:**
 
Currently, shuffle all music generates a playlist with all songs in a random order. Shuttle then plays them all once. I am hoping for an option, when enabled, for the next track to be truly random. In other words, pressing next track can repeat a song even if it was played before the current one. Previous track should always remember what was played up to however many is feasible.

**Comment by timusus** [comment]
I'm not that keen on this. It allows for songs to be played multiple times in one session (or even in a row), and some songs will be heard more frequently than others which will result in users complaining that the app isn't 'random enough'.
