### ISSUE TITLE
Queue disappearing

### ISSUE THREAD

**Issue by stkAnon** [timusus/Shuttle#404]
**Shuttle version:**
 
 `2.0.6 (Upgraded)`
Previous versions affected as well.
 
**Device, OS:**
 
Android 8.0, 8.1.0, 9.X reported.
Multiple devices reported.

**Description of bug:**
 
From reddit (2 individual posts/comments, 7 total upvotes):

>Pausing playback and switching to another app (or another app starting its own playback) will often cause the play queue to become empty on Android 8.1.

>https://imgur.com/a/UtZHPw6

>This started happening after a relatively recent major Android version update that added new power management features.

>I have not observed any clear correlation between this behavior and the duration of the pause, memory use during the pause, or activities and apps launched during the pause.

>I have the paid upgrade for Shuttle. The smooth UI is great, the automatic UI colour selection has been pretty cool since the algorithm started accounting for saturation and probable aesthetic appropriateness, and the little enhancements like the faded album art in the notification are great, but being unable to reliably listen to a queue you've set up is very nearly a deal-breaker for me.

>Same problem tested on 9.0 and 8.0 devices. It got slightly better when I turned off battery optimization for Shuttle, but that's not a viable long term solution.

https://www.reddit.com/r/shuttle/comments/9pnm1f/pausing_playback_and_switching_to_another_app_or/

On my own, I've found that the play queue will sometimes still be loaded back in if I wait a minute or so after reopening the app. This is pretty inconsistent though, it normally doesn't work if I touch the UI's navigation controls at all before it's loaded, and even when it does work I still need to wait for upwards of 30 seconds with an empty play queue, and then it still loses track of the position in the song.

Also, interestingly enough, even when the app is in the background, the control notification is gone, and the play queue is (would be) empty when I re-open the app, the playback controls on my Bluetooth headset can often get the song to pick back up where I paused it (after a brief delay).
 
**Steps to reproduce:**
 
 1. Launch Shuttle.
 2. Start a new play queue.
 3. Pause playback and exit Shuttle (in any order).
 4. Return to Shuttle.
 
**Expected outcome:**
 
Play queue is restored as before exiting the app, and position in current song is preserved and ready to resume.
 
**Observations/Actual Result:**
 
Play queue is empty.

https://imgur.com/a/UtZHPw6

Play queue will occasionally be restored after several dozen seconds of waiting if touch interface is not interacted with in that time, but play position in current song will likely have reverted to a previous state even in this case.

**Comment by timusus** [comment]
I've noticed this issue, introduced and since resolved in a recent beta version. @stkAnon can you just confirm that this is definitely happening in the stable version, and not a beta version?

Thanks for the report.

**Comment by stkAnon** [comment]
I haven't joined any beta-testing program AFAIK, and this has been happening on my phone for a number of months, over multiple versions through periodic Google Play updates.

Thank you for the app and for looking into this.

**Comment by timusus** [comment]
@stkAnon would you consider trying the beta, and let me know if this problem is resolved?

**Comment by balzabalza** [comment]
I don't have this issue on last beta.

**Comment by stkAnon** [comment]
Is there any way to install the beta from the Play store? I'd just rather not manually install an `.apk` on my daily driver.

**Comment by jugges** [comment]
@stkAnon Just join the beta testing program in the app's Google Play page

**Comment by stkAnon** [comment]
Alright, thank you. I haven't tested it that thoroughly yet, in part because the behaviour was made slightly less consistent by a minor Android upgrade in the interim, but it does seem to be fixed (or at least greatly improved) in 2.0.7-beta11.

**Comment by stkAnon** [comment]
Heh. The number for this issue is: 404/Queue not found.

Closing as it does seem to have been fixed.
