### ISSUE TITLE
Car Bluetooth / Android Auto issues

### ISSUE THREAD

**Issue by 5pirytus** [timusus/Shuttle#410]
**Shuttle version:**
 
 2.0.7-beta11
 
**Device, OS:**
 
Pixel 3 using latest Android 9.0 Pie

**Description of bug:**
 
When listenning to music in my car using Bluetooth, there is no information displayed other than "Not provided". And if I pause the music using the car controls, it always resumes a few seconds later.
Both of these issues do not happen with the non beta version of the app.

Also, I have a lot of tracks stored in my device and browsing in Android Auto, sometimes the list does not display all the albums or artists. This bug is very rare and I am not able to reproduce it... Unplugging and plugging back the device seems to solve it so far.

**Comment by 5pirytus** [comment]
Well, I'm very confused. The "not provided" about media info on the car display doesn't happen anymore.
I don't know why since nothing changed on my side. Weird.

**Comment by timusus** [comment]
Let me know if this issue reappears @5pirytus
