### ISSUE TITLE
Tracks skipped in Playing Queue

### ISSUE THREAD

**Issue by GeoZac** [timusus/Shuttle#415]
**Shuttle version:**
 
 v 2.0.7- beta11
 
**Device, OS:**
 
Redmi Note 5 running LineageOS  based custom ROM

**Description of bug:**
 
The first track of playing queue is skipped in some cases.
 
**Steps to reproduce:**
 
 1. Start playing any list (album, playlist) with Shuffle OFF and Repeat OFF 
 2. Let the last track play till end.
 3. Press play in now playing screen. 
 
**Expected outcome:**
 
The playback should start from track 1
 
**Observations/Actual Result:**
 
The playback starts from track 2

**Remarks:**
- Same behavior observed with headset controls.
- Bug reproducible with latest `dev `branch too.

**Comment by timusus** [comment]
@GeoZac perhaps the track cannot be played by `MediaPlayer`? Does this only happen for specific audio files?

**Comment by timusus** [comment]
@GeoZac can you post that video here?

**Comment by GeoZac** [comment]
Issue reproduced in v2.0.8-beta1
[Video](https://drive.google.com/open?id=1MzVA4WC-1rzLes9HCSBi2nD8S4m50pTC)

**Comment by pwd-github** [comment]
This is happening for me too. I'm able to go back and select the songs just fine. They're just being randomly skipped in the queue. I'm also seeing that the queue is being put into alphabetical order and the only way to restore is to swipe from memory and go back in via the notification. It's been doing my nut in.

**Comment by pwd-github** [comment]
@timusus

**Comment by timusus** [comment]
@pwd-github could you please write a separate issue for the 'alphabetical order' problem, and provide some more details?
