### ISSUE TITLE
Black scroll bar is extremely hard to see on dark theme and impossible to see on black background.

### ISSUE THREAD

**Issue by stkAnon** [timusus/Shuttle#420]
**Shuttle version:**
 
 v2.0.7-beta11
 
**Device, OS:**
 
Blackberry KeyONE, Android 8.1

**Description of bug:**
 
Within a single second of opening, the scroll bar will flicker, autohide, and invariably turn black when it returns.

This makes it aesthetically displeasing, as well as difficult to impossible to see when using the dark or black theme bases, especially when outdoors or with energy-efficient screen brightness settings.

It will temporarily return to the primary colour of the theme when being dragged. However, it is very difficult to find it and drag it when it is black.
 
**Steps to reproduce:**
 
 1. Open any page with a scroll bar.
 2. Wait, or try to scroll.
 
**Expected outcome:**
 
![screenshot_20190128-131913](https://user-images.githubusercontent.com/8258259/51867566-b549de00-2300-11e9-9c75-d05bbded696e.png)

**Observations/Actual Result:**
 
 
![screenshot_20190128-131921](https://user-images.githubusercontent.com/8258259/51867624-d14d7f80-2300-11e9-9669-cf3fab15ae44.png)
![screenshot_20190128-132054](https://user-images.githubusercontent.com/8258259/51867633-d90d2400-2300-11e9-85b8-98abfab7bacc.png)

**Comment by GeoZac** [comment]
@timusus This a single line fix,do I need to make a pull request for it or should i just post here so that you can add it to a future release?
