### ISSUE TITLE
Crash on orientation changes

### ISSUE THREAD

**Issue by lucavallerini** [timusus/Shuttle#423]
**Shuttle version:**
 
 v2.0.8-beta2
 
**Device, OS:**
 
Moto G6 Plus, Oreo 8.0

**Description of bug:**
 
Shuttle crashes when you change orientation. Here the stack trace of the crash: [shuttle-orientation-crash.txt](https://github.com/timusus/Shuttle/files/2851532/shuttle-orientation-crash.txt)
 
**Steps to reproduce:**
 
 1. Open Shuttle
 2. Change orientation
 3. App crashes
 
**Expected outcome:**
 
App should not crash after changing orientation.
 
**Observations/Actual Result:**
 
App crashes on orientation change.

**Comment by timusus** [comment]
This should be resolved with 2.0.8-beta4
