### ISSUE TITLE
Shuttle+ fails to detect some audio files, but other music players do.

### ISSUE THREAD

**Issue by shymega** [timusus/Shuttle#424]
**Shuttle version:**
 
 v2.0.7 (Upgraded)
 
**Device, OS:**
 
Blackberry KeyONE, Android 8.1.0

**Description of bug:**
 
Other music players detect my podcasts directory, but Shuttle does not detect them.
They are in OGG format, and play fine with other media players.
 
**Steps to reproduce:**
 
 1. Download a BBC podcast to a podcasts directory on the phone. (OGG format)
 2. Trigger a media scan, or wait for one.
 3. Open Shuttle+, try to open the podcast for playback.
 
**Expected outcome:**
 
I'd expect the BBC podcast (or any podcast really, they all seem to fail to appear in Shuttle) to appear in the Shuttle+ library view.
 
**Observations/Actual Result:**

No podcasts are seen in Shuttle+, but they have worked before in older versions.
In other players, such as Google Play Music, or the stock music player, do not fail to detect the podcasts. I do not believe this is a Media Storage issue, or to do with `.nomedia` files.

**Comment by GeoZac** [comment]
What happens when you try to open the said file in using the in-app Folger navigation?

**Comment by shymega** [comment]
I get this error, similar to #371.

"The playlist is empty. Long press on an artist, album or song and press 'add to playlist', or + icon to get started."

**Comment by timusus** [comment]
This does sound very much like a MediaStore issue to me. Playing in GoneMad doesn't rule much out because it doesn't use the MediaStore. Which is the 'stock' player you're using?

What directory are the files held in? If you move them to say, storage/music, are they usable?

**Comment by shymega** [comment]
OK. There is no 'stock' player on my Blackberry. I installed Shuttle to provide that. What did you mean by 'GoneMad'?

The music directory is in /sdcard/Media/Music. Its synchronised overnight with Syncthing. I'll give it a go moving to another directory; will report back soon.

**Comment by shymega** [comment]
I found a stock music player on F-Droid. That shows the podcasts correctly. I also moved the directory to `/sdcard/Music` as well. 

The media cache has been rebuilt, but Shuttle is still not showing the podcasts themselves. I'm quite sure this used to work, but I may well be mistaken.

As other media players find the podcasts correctly, I do wonder if its a bug in Shuttle itself.. perhaps.

**Comment by shymega** [comment]
I've just tried moving _just_ the `/sdcard/Media/music/podcasts` directory to the root of the sdcard. Its still not recognized by Shuttle. I'm not really sure how to proceed... is there a way to query the MediaStore to see if it can "see" the podcasts?

**Comment by GeoZac** [comment]
@shymega Could you share from where you access these said podcasts(if available on a public domain) , I tried a OGG Vorbis1 standard file and was recognized and played well with Shuttle. If I'm able to reproduce this issue,it may shed more light into the issue

**Comment by shymega** [comment]
@GeoZac [Here](https://thebugcast.org/2019/02/16/551-daves-faves/) is a podcast I've been trying to listen to - there's a MP3 and OGG version -- I use the OGG one (and all of my music is encoded in OGG, should have mentioned that).

**Comment by shymega** [comment]
Solved the problem.. I checked the changelog, and as of 2.0.5, podcasts are in a separate playlist, so that does explain a lot!

There's no option I can see that disables that behaviour, though. Perhaps in future releases, an option to opt-out of said behaviour could be added?

Closing for now.
