### ISSUE TITLE
Crashing alert. App shortcuts

### ISSUE THREAD

**Issue by Linguss** [timusus/Shuttle#426]
**Shuttle+:**
Version: 2.0.8-beta3 (5786)
Moto G5plus Android- 9.x.x
               
                *_*Bug*_*
The app shortcut is not working...Eg shuffle all or Play. The app just crashed after taping on them.

https://del.dog/pijaxoquza
https://del.dog/ucoyemadof
https://del.dog/iguhiqovab

**Comment by timusus** [comment]
Resolved in 2.0.8-beta4
