### ISSUE TITLE
Notification destroyed and recreated when changing songs/pausing

### ISSUE THREAD

**Issue by neekless** [timusus/Shuttle#427]
**Shuttle version:**
 
 v2.0.8-beta3 and beta4, possibly started earlier
 
**Device, OS:**
 
Pixel 2XL Android 9 (HavocOS custom rom)

**Description of bug:**
 
Notification destroyed and recreated when changing songs/pausing using notification controls. 
 
**Steps to reproduce:**
 
 1. Play music
 2. Pause song/change song using notification controls
 
**Expected outcome:**
 
Notification doesn't get destroyed and recreated repeatedly
 
**Observations/Actual Result:**
 
Notification gets destroyed and recreated repeatedly.
Reference video here: https://drive.google.com/open?id=1ObJzajHo_qVyWXroO_eXqeTbNwVTKEcR

If this is intended behavior, please close this issue.

**Comment by timusus** [comment]
Thanks for the report.

This was an intentional (but temporary) test, to see if this would resolve a particular crash. It does, but in a pretty annoying way! I'm looking for a proper fix for this issue now.

**Comment by neekless** [comment]
Thanks for the response! This isn't high priority so don't worry about it.

On another note, idk if you can tell from the video, often the artwork in the notification does not match the song playing. The artwork seems to be one step behind, showing the previous song's artwork instead of the current song's. Is this a mediastore issue? Should I open another issue?
