### ISSUE TITLE
Error:Execution failed for task ':app:processAmazonFreeReleaseGoogleServices'.

### ISSUE THREAD

**Issue by Vikram984511** [timusus/Shuttle#43]
Sir please help me solve this issue.

File google-services.json is missing. The Google Services Plugin cannot function without it.
Searched Location:
C:\Users\user\Shuttle\app\src\amazonFree\release\google-services.json
C:\Users\user\Shuttle\app\src\release\amazonFree\google-services.json
C:\Users\user\Shuttle\app\src\amazonFree\google-services.json
C:\Users\user\Shuttle\app\src\release\google-services.json
C:\Users\user\Shuttle\app\google-services.json

**Comment by timusus** [comment]
Please refer to the 'getting started' section of CONTRIBUTING.md
