### ISSUE TITLE
The APK file outputs\apk\free\release\app-free-release.apk does not exist on disk.

### ISSUE THREAD

**Issue by dholiya** [timusus/Shuttle#435]
**Shuttle version:**
 
 v1.x.x
 
**Device, OS:**
 
Device info here

**Description of bug:**
 
Bug description here
 
**Steps to reproduce:**
 
 1. Step 1
 2. Step 2
 3. Step 3
 
**Expected outcome:**
 
Expected outcome here
 
**Observations/Actual Result:**
 
 Observations here

**Comment by GeoZac** [comment]
Read [here](https://github.com/timusus/Shuttle/blob/dev/.github/CONTRIBUTING.md#getting-started)
