### ISSUE TITLE
Regarding the Shuffle & Replay Button

### ISSUE THREAD

**Issue by Eksx3** [timusus/Shuttle#436]
**Shuttle version:**
 
 v2.0.8
 
**Device, OS:**
 
GALAXY S9+ 
One UI 1.0
v9

**Description of bug:**

Using custom theme options, shuffle & replay Symbols are a constant black, unable to tell if turned on. 

more detailed description and Observation: https://github.com/timusus/Shuttle/issues/432

**Steps to reproduce:**
 
'Now Playing'
'Press shuffle/repeat symbol'
 
**Expected outcome:**

Color change indicating whether the symbols are pressed.

**Observations/Actual Result:**
 
Observations: 
I noticed that it does show an accent color but only if the Artwork Color Pallete option is used.

**Comment by timusus** [comment]
Duplicate of #432
