### ISSUE TITLE
No song number is displayed for new songs

### ISSUE THREAD

**Issue by xoner** [timusus/Shuttle#437]
**Shuttle version:**
 
 v2.0.8 (shuttle+)
 
**Device, OS:**
 
Xiaomi Mi A1, Android 9

**Description of bug:**
 
When new music is added, song number is not correctly displayed until the phone reboots. All new songs are added with the song number 0.
 
**Steps to reproduce:**

1. Copy files throug usb or from an external program (f.e. I use esFileExplorer) to the Music folder of the phone.
2. Open Shuttle
3. The songs are added but every song has Track number 0
4. I've tried to completely close application and restart it and all songs still display track number 0
 
**Expected outcome:**
 
Song number contained in metadata should be displayed and songs ordered bassed on song number.

![files-added-after-reboot](https://user-images.githubusercontent.com/140173/53431848-b189a400-39f1-11e9-9e73-df774e05ed38.png)

(The image displayed is the from a new album added, after a phone reboot)

**Observations/Actual Result:**
 
All songs display number 0 and order is random.

![files-added-no-reboot](https://user-images.githubusercontent.com/140173/53431734-6d969f00-39f1-11e9-8469-efe2c895e85c.png)

**Comment by timusus** [comment]
This is a problem with the Android MediaScanner or MediaStore, and not something I can resolve.

You might have success by 'rescanning' the folders containing the new music via the folder browser.
