### ISSUE TITLE
Garbled Text in Song and Album Info

### ISSUE THREAD

**Issue by Siheyuan98** [timusus/Shuttle#446]
**Shuttle version:**
 
 v2.0.6
 
**Device, OS:**
 
Device: Redmi Note 4
Android Version: 7.1.2

**Description of bug:**
 
An album is placed in a folder like the following:
```
Motörhead - Motörhead
\-- 1. Motörhead - Motörhead.mp3
\-- 2. Vibrator - Motörhead.mp3
\-- 3. Lost Johnny - Motörhead.mp3
\-- 4. Iron Horse  Born to Lose - Motörhead.mp3
\-- 5. White Line Fever - Motörhead.mp3
\-- 6. Keep Us on the Road - Motörhead.mp3 
\-- 7. The Watcher - Motörhead.mp3
\-- 8. The Train Kept a-Rollin' - Motörhead.mp3 
```

In Shuttle, track 2~8 are placed on the Album correctly:
![4](https://user-images.githubusercontent.com/6215580/54823131-d667f300-4ce1-11e9-9a35-975a8e723891.png)

... While track 1 is in a separate album with garbled information.

(But tags can still be accessed)

![1](https://user-images.githubusercontent.com/6215580/54823119-d0721200-4ce1-11e9-99cb-9c97b3d1cf42.png)

![2](https://user-images.githubusercontent.com/6215580/54823137-d8ca4d00-4ce1-11e9-8ddb-b9007e8dabb7.png)

![3](https://user-images.githubusercontent.com/6215580/54823142-db2ca700-4ce1-11e9-8bfc-19bc5e3e76fb.png)
 
**Steps to reproduce:**
 
 1. Add said folder to storage: `/storage/emulated/0/Music/Motörhead - Motörhead`
 2. Open "Album" tab of Shuttle
 3. Garbled information found
 
**Expected outcome:**
 
All 8 tracks are placed in the same album with correct information
 
**Observations/Actual Result:**
 
Track 1 is placed in a separate album with garbled information

**Comment by timusus** [comment]
This is common with custom ROM's and ROM's which don't properly support their fonts. I don't believe this is something that can be fixed in Shuttle itself.
