### ISSUE TITLE
Add random sort order

### ISSUE THREAD

**Issue by vext01** [timusus/Shuttle#447]
Hi,

Fantastic player!

I have a feature request. Could we add an option to sort any of the lists (artists, albums, ...) by random order.

Often I don't know what I want to listen to, and end up just scrolling the artist list, browsing for something I fancy. The problem is, I always end up looking at A, B and C, and sometimes scroll down to (inevitably, for some reason) S.

It'd be neat if the random option re-shuffled the list every time you open it. Then all items get a fair chance at being seen in the list.

Thanks

**Comment by timusus** [comment]
I think you can probably just press 'shuffle all' and see what comes up, if you want random. If you're going to select a song you want to hear by looking at them, you're removing the random element yourself to a large degree.
