### ISSUE TITLE
"Shuttle service running..." notification when pressing the "next track" button in the main notification

### ISSUE THREAD

**Issue by ultramailman** [timusus/Shuttle#449]
**Shuttle version:**
 
 v2.0.10
 
**Device, OS:**
 
Pixel 3 Android 9

**Description of bug:**
 
When pressing the "next track" arrow button in the shuttle notification, it creates a second notification with the message

> Shuttle+
> Shuttle+
> Shuttle service running...
 
**Steps to reproduce:**
 
 1. Play a song
 2. Pull down notification panel or view notification in lock screen
 3. Press "next track" arrow button in the shuttle notification
 
**Expected outcome:**
 
Shuttle starts playing the next song
 
**Observations/Actual Result:**
 
Shuttle starts playing the next song, but a new notification as described above is created. The second notification disappears after about 10 seconds.

**Comment by timusus** [comment]
This is intentional, to workaround a framework bug in Android 9.9

**Comment by neodraig** [comment]
I'm on Android 10, is this still necessary?
