### ISSUE TITLE
App crashes when tag editor is used

### ISSUE THREAD

**Issue by jubreal** [timusus/Shuttle#450]
#### Expected behavior

Users should be able to be able to edit songs info with the help of the app successfully without the app crashing. 

#### Actual behavior

The application closes and crashed when user is using tag editor. 

#### How to reproduce

1. Download and install the latest release of the app. 

2. Launch the app.

3. Grant all permissions.

4. Navigate to the list of songs and play any song, then click on the 3-horizontal dots in front of a song.

5. Click on the "Edit Tags" option.

6. Make an change to name of song or album or anything , then click on "Save"

It will be observed that the app crashes and closes.  Hence, the bug. 

* Browser: Shuttle Player version 2.0.11 beta1
* Operating system: android version 6.0

#### Recording Of The Bug
https://youtu.be/tWdn9DCsxxI

#### LOG
``` 04-01 07:35:37.674 E/ShuttleApplication(31680): Failed to repair media store year
04-01 07:35:37.674 E/ShuttleApplication(31680): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����
04-01 07:37:10.678 I/NoteEdit(30976): * Browser: Shuttle Player version 2.0.11 beta1
04-01 07:40:51.853 E/ShuttleApplication(32280): Failed to repair media store year
04-01 07:40:51.853 E/ShuttleApplication(32280): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����
04-01 07:41:14.696 E/ShuttleApplication(32430): Failed to repair media store year
04-01 07:41:14.696 E/ShuttleApplication(32430): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����
04-01 07:46:08.365 D/MusicService(32430): onStartCommand() Action: com.simplecityapps.shuttle.service_command.shutdown, Command: null

**Comment by timusus** [comment]
Thanks for the detailed report. These logs don't seem to be related to this crash. It has been fixed and will be released in the next version.
