### ISSUE TITLE
App crashes when Go To Artist is clicked on

### ISSUE THREAD

**Issue by jubreal** [timusus/Shuttle#451]
#### Expected behavior

Users should be able to be able to navigate to artist info when the 'Artist' is selected under "Go To" option in the app without the app crashing. 

#### Actual behavior

The application closes and crashed when the 'Artist' is selected under the "Go To" option. 

#### How to reproduce

1. Download and install the latest release of the app. 

2. Launch the app.

3. Grant all permissions.

4. Navigate to the list of songs and play any song, then click on the 3-horizontal dots in front of a song.

5. Click on the "Go To" option.

6. Click on the "Artist"

It will be observed that the app crashes and closes.  Hence, the bug. 

* Browser: Shuttle Player version 2.0.11 beta1
* Operating system: android version 6.0

#### Recording Of The Bug

https://youtu.be/hsZsSqX2zJ4
#### LOG
``` 04-01 08:31:40.231 E/ShuttleApplication(11637): Failed to repair media store year
04-01 08:31:40.231 E/ShuttleApplication(11637): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����
04-01 08:32:01.379 E/ShuttleApplication(11858): Failed to repair media store year
04-01 08:32:01.379 E/ShuttleApplication(11858): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����

**Comment by timusus** [comment]
Thanks for the detailed report. Fixed for the next update.
