### ISSUE TITLE
App crashes when trying to set song as ringtone

### ISSUE THREAD

**Issue by jubreal** [timusus/Shuttle#452]
#### Expected behavior

Users should be able to be able to set a song as ringtone without the app crashing.

#### Actual behavior

The application closes and crashed when a song is set as ringtone on the app

#### How to reproduce

1. Download and install the latest release of the app. 

2. Launch the app.

3. Grant all permissions.

4. Navigate to the list of songs and play any song, then click on the 3-horizontal dots in front of a song.

5. Click on the "Set As Ringtone" option.

It will be observed that the app crashes and closes.  Hence, the bug. 

* Browser: Shuttle Player version 2.0.11 beta1
* Operating system: android version 6.0

#### Recording Of The Bug
https://youtu.be/F-9abUHnakQ

#### LOG
``` 04-01 09:02:05.328 E/ShuttleApplication(20600): Failed to repair media store year
04-01 09:02:05.328 E/ShuttleApplication(20600): Throwable: /storage/emulated/0/WhatsApp/Media/WhatsApp Audio/AUD-20190218-WA0000.m4a:Unable to find next atom because identifier is invalid ����

**Comment by timusus** [comment]
Thanks for the report. This has been fixed for the next update.
