### ISSUE TITLE
No Storage Option on Shuttle+ AndroidQBeta2

### ISSUE THREAD

**Issue by tonkatsuki** [timusus/Shuttle#457]
**Shuttle version:**
 
 v2.0.10 (Upgraded)
 
**Device, OS:**
 
Pixel 3 XL (crosshatch) with Android Q Beta 2

**Description of bug:**
 
If you go to Folders tab the only folder that shows up is Android with data/media/obb under it. I cannot enable storage permissions for the app in Android Q Settings UI so I cannot browse my folders. Songs view works fine. Note when I upgraded to Android Q Beta 1 a week or so ago, this worked fine but I relocked by bootloader this morning and therefore my settings didn't carry over so now I can't browse folders so this app is kind of useless for me now :(
 
**Steps to reproduce:**
 
 1. Open Shuttle+
 2. Navigate to settings and enable Folder view if not enabled
 3. Open Folders tab
 
**Expected outcome:**
 
Should be able to see folders
 
**Observations/Actual Result:**
 
 Cannot see folders :(

**Comment by kjkinnunen** [comment]
This can be ignored now that scoped storage is being disabled for Android Q on the next beta build, so this won't be a problem until the next next android release..
