### ISSUE TITLE
Tags can't be edited on Shuttle Music Player v2.0.12-beta1 (free) 

### ISSUE THREAD

**Issue by chrisbarth01** [timusus/Shuttle#463]
Expected behavior 
I intended to edit the tag/song-info of one of my songs and I expected the song's tag/song-info to be successfully updated when I click on the 'save' option. 

---

#### Actual behavior 
After I edited the tag/song-info, the tag/song-info can not be saved because when I click on the 'save' button, nothing happens.

---

#### How to reproduce 
- Download, install and launch the latest version of the app
- Swipe from the right to the left till you get to the end which is the 'SONGS' feature
- Click on any of the three vertically arranged dots which is in line with each and every song
- Select 'Edit tags' 
- Edit the tags and click on 'save'
- Observe the bug. 

---

Device: Gionee f100s 
Android version: 6.0
App version: 2.0.12-beta1 (free) 

---

#### Recording of the bug
https://youtu.be/B3oTbMUbDGY

**Comment by chrisbarth01** [comment]
And when the older values are still displayed, it means that the edit isn't made.... If the edit is made, the song info should change (the song name, artist, etc). 
However, the save button doesn't even seems to function at all, but when I click on the close button, the close button functions very well.

**Comment by timusus** [comment]
Resolved for v2.0.12-beta2
