### ISSUE TITLE
Shuttle player crashes when trying to upgrade to Shuttle+

### ISSUE THREAD

**Issue by jubreal** [timusus/Shuttle#464]
#### Expected behavior
Users should be able to upgrade their shuttle music player app from the free version using the upgrade feature in the free beta app.

#### Actual behavior
The application closes and crashed when user click on the upgrade feature.

#### How to reproduce
- Launch the app.

- Grant all permissions.

- Click on the Menu button (3-horizontal lines in the top left corner of the app)

- Click on the "Settings" option

- Click on "Upgrade to Shuttle+" and then click on "UPGRADE"

It will be observed that the app crashes and closes. Hence, the bug.

Browser: Shuttle Player version 2.0.12-beta1
Operating system: Android version 6.0

#### Recordings Of The Bug
https://youtu.be/LPq5BZsNquU

**Comment by timusus** [comment]
@jubreal the title doesn't match the description, and there is no 2.0.12-beta2. Can you clarify?

**Comment by jubreal** [comment]
Sorry about the mixup, I've made corrections to the title, and the version of the app is the newest release v2.0.12-beta1 (free). 
I would have provided the crash log, but unfortunately, I don't have my adb device present with me currently. Let me know if you need anything else, please. Thanks

**Comment by timusus** [comment]
No problem, thank you for the report

**Comment by jubreal** [comment]
You are welcome.

**Comment by timusus** [comment]
Fixed in v2.0.12-beta2
