### ISSUE TITLE
Feature request: list album artists

### ISSUE THREAD

**Issue by baloe** [timusus/Shuttle#470]
**Shuttle version:**
 
 v2.0.11
 
**Feature request:**

It would be great to have the option to have album artists listed in the artist view.

**Comment by timusus** [comment]
Can you elaborate? The artist view currently is a list of album-artists.

**Comment by baloe** [comment]
You are right; I was mistaken being misled by some false metadata for which as I now know some Android service is to blame. 
Sorry for the inconvenience, I do enjoy using shuttle!
