### ISSUE TITLE
Android 10 - Playlists missing

### ISSUE THREAD

**Issue by daedos** [timusus/Shuttle#477]
**Shuttle version:**
  v2.0.11
 
**Device, OS:**
 Pixel 3a.  Android 10 build QP1A.190711.020

**Description of bug:**
 After upgrading to Android 10 my playlists have disappeared
 
**Steps to reproduce:**
  1. Upgrade to Android 10
 
**Expected outcome:**
 Playlists remain as they were
 
**Observations/Actual Result:**
I've tried reinstalling Shuttle+,  removing the playlist m3u files and music, re-syncing all music/playlists via DoubleTwist.   Playlist still empty.  The playlist m3u files looks fine.  Phonograph and Pulsar music apps do a bit better, they see the playlists but not all the tracks within e.g. show 128 instead of 3,200 tracks.

/storage/emulated/0/Music    <- m3u playlists here

Has Android 10 changed something re playlists?

**Comment by fhmr** [comment]
I had the same issue. I was able to add songs to existing playlists and it recognised when I was adding duplicate songs but none of the playlists themselves would show up in the side menu or the playlist tab. When I updated Shuttle to the beta the issue went away.

**Comment by daedos** [comment]
> When I updated Shuttle to the beta the issue went away.

Star.  I tried the beta and my playlists are back.  

Of note I also sorted the partial playlist problem.  I use doubletwist to sync my iTunes playlists to my Pixel. All was working fine until Android 10 where only a handful of songs were present.  Noticed those present were in the root of the Music folder.  Best guess is that the Android 10 media scanner no longer recognises backslashes in the paths.  Manually modifying the m3u playlist files to use forward slashes solved it.  Hope this might help someone.

**Comment by jeremycincy1987** [comment]
Probably because they added a new strict copyright policy for Android versions 10 and up that restrict you from creating playlists unless you pay monthly for a music app

**Comment by timusus** [comment]
This has nothing to do with copyright policy..

Android 10 made changes to how files are accessed by apps.  It looks like in doing so, they broke the MediaScanner, and it isn't able to effectively import m3u playlists - depending on where the files are located.

This is outside the scope of Shuttle. Shuttle is just reflecting what is available in the MediaStore.
