### ISSUE TITLE
Playlists not accessible

### ISSUE THREAD

**Issue by FuzzyBoots** [timusus/Shuttle#482]
**Shuttle version:**
 
 v2.0.11
 
**Device, OS:**
 
Pixel 3a, 10 / Q

**Description of bug:**
 
Playlists exist, and can be added to, or overridden, but aren't accessible by the main menu. Tapping on Playlists off of the hamburger menu does nothing.
 
**Steps to reproduce:**
 
 1. Open Shuttle
 2. Tap the hamburger menu in the upper left
 3. Tap Playlists
 
**Expected outcome:**
 
Playlists on phone open
 
**Observations/Actual Result:**
 
 Nothing happens. Hamburger menu stays open.

**Comment by DJArghlex** [comment]
Can confirm, this is broken on Essential PH1, also running Q. Just upgraded from P.

**Comment by daedos** [comment]
tried the beta?  I had playlist issues too ([link](https://github.com/timusus/Shuttle/issues/477)) after migrating to Android 10.
