### ISSUE TITLE
Special characters in albums and track names

### ISSUE THREAD

**Issue by Nowena** [timusus/Shuttle#501]
Shuttle+ 2.0.15
 Moto G7 android 10

Some album and track names with special characters get messed up for some reason but when I look at the tags, they look fine and it's driving me crazy.
 
For example take Ænima by Tool, the album is split in two with some tracks under Ænima and the rest as Ćnima
![Screenshot_20200607-185819](https://user-images.githubusercontent.com/52898460/83983076-161ff800-a8f1-11ea-8fb6-0ecb35bebba1.png)

Another example is an album by Sed Non Satiata, the correct title is Mappō
![Screenshot_20200607-190117](https://user-images.githubusercontent.com/52898460/83983104-57180c80-a8f1-11ea-8255-623a7a60297f.png)

And for some tracks example, there's this Gattaca release, the correct titles are as evidenced by the tags: Rozděl a panuj, Kódy, čísla, znaky and Tohle není moje město
![Screenshot_20200607-190338](https://user-images.githubusercontent.com/52898460/83983150-a78f6a00-a8f1-11ea-8a5b-d76da8cbe4ae.png)
 
All those special characters shouldn't be altered and look as they do in the tags but instead they all look messed up and scrobble to last.fm that way.

**Comment by timusus** [comment]
This is an issue with the MediaStore. I haven't found a way to work around this problem. I have the same problem with Ænima and it drives me insane as well.
