### ISSUE TITLE
Set dev branch as default branch

### ISSUE THREAD

**Issue by deletescape** [timusus/Shuttle#51]
> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.  
> _**Quoting from GitHub Repo settings**_

Would make it a lot clearer that the branch PRs should go on is the dev branch. It also makes sense having it as the default branch as it is always up to date with the latest development.

**Comment by timusus** [comment]
Totally agree, will do.
