### ISSUE TITLE
Privacy leak in Shuttle+ ?

### ISSUE THREAD

**Issue by iiitomo** [timusus/Shuttle#531]
**Shuttle version:**
 
 v2.0.15 from F-Droid
 
**Description of bug:**
 
I'm surprised to discover that Shuttle+ connects to lastfm-img2.akamaized.net , and this is reported /blocked as a privacy leak by TrackerControl.
Please can you remove this Akamai tracker, or explain why it is necessary?

**Comment by timusus** [comment]
Shuttle uses Last.fm for artist/album images. I'm not familiar with 'Akamai' trackers, feel free to fill me in. 

The code is open source so you're free to make any changes you like.

**Comment by duanemoody** [comment]
Akamai is one of the older CDNs which mirrors for load bearing the way Cloudflare does.
