### ISSUE TITLE
Playlist Longer Than 30 Songs?

### ISSUE THREAD

**Issue by HonestAbe7** [timusus/Shuttle#536]
Love the F-Droid version of this app!

Is there any way to have more than 30 songs in one playlist? I want to play more songs continuously without making a separate playlist.

**Comment by timusus** [comment]
Shuttle has no limitation on the length of playlists

**Comment by HonestAbe7** [comment]
Then why can't I add any songs after adding 30 songs to a playlist?

**Comment by timusus** [comment]
I'm not sure. Can you provide more details? What happens when you try? What tells you that there's a 30 song limit?

**Comment by HonestAbe7** [comment]
Because I can't add song 31 to a playlist
    On Saturday, October 2, 2021, 08:35:00 PM EDT, Tim Malseed ***@***.***> wrote:  
 
 


I'm not sure. Can you provide more details? What happens when you try? What tells you that there's a 30 song limit?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by timusus** [comment]
Could you please be more specific? As I said, there's no 30 song limit in Shuttle, so I don't know why this happens for you.

**Comment by HonestAbe7** [comment]
I don't know how I can be more specific for you. If you make a playlist and add 30 songs it can't successfully add the 31st song.
    On Saturday, October 2, 2021, 10:41:55 PM EDT, Tim Malseed ***@***.***> wrote:  
 
 


Could you please be more specific? As I said, there's no 30 song limit in Shuttle, so I don't know why this happens for you.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by timusus** [comment]
When you attempt to add a song to a playlist, what happens? Does the app display an error message? What does the message say?

How are you trying to add songs to the playlist? Does the same issue occur if you use multi-select, and try to create a playlist out of a few albums (containing in total more than 30 songs)?

Which device and OS are you using? Has this issue only recently started occurring?

**Comment by HonestAbe7** [comment]
When I try to add the 31st song to the playlist it just doesn't take. Plus no error message too. It doesn't matter if I try multi-select too. I tried other media players and they have the same issue except VLC which the playback is not that great. I am using an Android 10 LG phone.


    On Monday, October 4, 2021, 12:42:51 AM EDT, Tim Malseed ***@***.***> wrote:  
 
 


When you attempt to add a song to a playlist, what happens? Does the app display an error message? What does the message say?

How are you trying to add songs to the playlist? Does the same issue occur if you use multi-select, and try to create a playlist out of a few albums (containing in total more than 30 songs)?

Which device and OS are you using? Has this issue only recently started occurring?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
