### ISSUE TITLE
Artwork in notification blinks

### ISSUE THREAD

**Issue by deletescape** [timusus/Shuttle#54]
A user (trying shuttle for the first time) reported a small bug directly to me, including a screen recording.

> "not a big thing..but why that artwork blinks when play/pause"

![shuttle_blink](https://cloud.githubusercontent.com/assets/13785669/23547359/2ee04cfe-0003-11e7-8b39-9266b592b962.gif)

**Comment by timusus** [comment]
No longer an issue
