### ISSUE TITLE
The dot on the progress bar goes off the card when listening to an album.

### ISSUE THREAD

**Issue by Justin00015** [timusus/Shuttle#55]
#17 While listening to an album, the dot on the progress bar goes off the card. It's a minor issue, but I just wanted to inform you.﻿
![17 - 1](https://cloud.githubusercontent.com/assets/26168814/23557668/c207bcec-fffe-11e6-80e6-4b48098f07e9.png)

**Comment by timusus** [comment]
I've made some changes to fix this.. Let me know if it's not fixed when v1.6.5-beta3 comes out.

**Comment by timusus** [comment]
Reopening, since ca6596b7b9721ed2a667cbdc0c575f321abecbae was reverted.

**Comment by timusus** [comment]
@Justin00015 does this happen every time, or just occasionally?

**Comment by geecko86** [comment]
I was not able to reproduce this on my Nexus 9 running N.

**Comment by Justin00015** [comment]
I think it is an occasional glitch.

**Comment by timusus** [comment]
The tablet layout has been nerfed in the latest commit, and will be rebuilt. This issue is unlikely to pop up again.
