### ISSUE TITLE
WhatsApp image download starts music

### ISSUE THREAD

**Issue by pavlejoksovic** [timusus/Shuttle#57]
I have the following problem with Shuttle+: When I download an image in a WhatsApp group chat the music starts playing. What could cause this? 

I'm on Moto Z Play running Android 6.0.1 and have the 1.6.4 version of Shuttle+

**Comment by timusus** [comment]
Can you reproduce the issue consistently? 

Not sure if this is a WhatsApp problem, a system problem or a Shuttle problem. 

Can you try closing Shuttle and clearing it from recents, then playing a song in Play Music, then pausing it, then try to reproduce the issue and see if Play Music starts playing?

**Comment by pavlejoksovic** [comment]
I previously disabled the play music app. I enabled it now, and did what you asked me to do. The problem is gone now. What a weird bug...
