### ISSUE TITLE
Show Changelog on App Launch

### ISSUE THREAD

**Issue by timusus** [timusus/Shuttle#66]
When a new version of the app is launched for the first time, it would be good to show the changelog, with an option to close, and perhaps a checkbox with 'don't show changelog on launch' or something..

An entry will also need to be made in Settings to toggle this option.

**Comment by flamurimeri** [comment]
> An entry will also need to be made in Settings to toggle this option.

i think changelog should be in support category not in settings
maybe more serious it will be that option

**Comment by timusus** [comment]
@flamurimeri yes, you're probably right. Something to consider when this is implemented.

**Comment by geecko86** [comment]
Pro-tip: adding a "rate the app" button to the changelog dialog is a good way to get reviews, as users feel grateful for the new features.

**Comment by timusus** [comment]
That is a great tip!
