### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [timusus/Shuttle#7]
Would you consider publishing the `.apk` file here at Github – for folks without Playstore access?

**Comment by timusus** [comment]
OK, will do.

**Comment by vkotovv** [comment]
Maybe it's a good idea to use something like https://f-droid.org/ ?

**Comment by IzzySoft** [comment]
@vkotovv sure, that would be great – but takes a while to get the app listed. What I had in mind was to put it into [my repo](https://android.izzysoft.de/repo), which you can use with the F-Droid client :smiley_cat:

**Comment by Jawnnypoo** [comment]
This app won't be permitted on F-Droid unfortunately due to its dependence on Firebase/Google Play Services which is not open source.

**Comment by timusus** [comment]
Now available on the releases page.

**Comment by IzzySoft** [comment]
@timusus could it be you forgot to keep it up? Tha last release having an `.apk` attached is v1.6.7. Could you please pick up again? Starting with the latest release should suffice :wink:

**Comment by timusus** [comment]
@IzzySoft I've had some trouble with the CI tool I was using, so I've been manually uploading apk's to the Play Store. I'll try and remember to update the GH releases.

**Comment by IzzySoft** [comment]
Thanks a lot, @timusus – in case you forget again and I notice, I'll just drop a note again :wink:
