### ISSUE TITLE
Make the album art container square in Now Playing UI

### ISSUE THREAD

**Issue by ArshBunny** [timusus/Shuttle#71]
The Now Playing screen currently either crops the album art horizontally or fills the empty space at the top and bottom with a [blur](https://archive.org/download/shuttle-issue/album-art.png). Reducing the height of the container could also save some space in the settings. Hopefully, this could be included in the commit mentioned in #39.

**Comment by timusus** [comment]
This isn't really possible. Given the vast array of device sizes, with different screen dimensions and aspect ratios, there is no way to have square artwork while ensuring that there is enough room to display the text and buttons properly.

What do you mean 'save some space in the settings'?

**Comment by ArshBunny** [comment]
Thanks for the response. There is a toggle under artwork settings to crop the album art to fill the available space. I figured it would become obsolete if the artwork space could be made to be a square.

**Comment by timusus** [comment]
I've actually had another think about this. If you have a look at the `now-playing-ui` branch, you'll see the artwork is now sqaure (achieved via constraint layout aspect ratio).

**Comment by timusus** [comment]
Done in dev.
