### ISSUE TITLE
Albums with no album artist are separated into separate albums

### ISSUE THREAD

**Issue by Pixelguin** [timusus/Shuttle#73]
* **Shuttle version:**
1.6.5-b4
 * **Device, OS:**
 Moto E2, 7.1.1
 * **Description of bug:**
Albums with no entry for their album artist are now considered separate albums. If this is intentional then disregard this.
 * **Steps to reproduce:**
Create album with no album artist tag.
 * **Expected outcome:**
1 album without an album artist tag.
 * **Observations (actual outcome):**
Multiple albums for each track artist.

**Comment by timusus** [comment]
Not entirely intentional. There have been some recent changes in this area - this may be an edge case that needs to be looked at. I'll come back to this one.

**Comment by timusus** [comment]
@Pixelguin it's not quite clear to me how to replicate this issue:

>1. Create album with no album artist tag.
>2. 1 album without an album artist tag.

Steps 1 & 2 look identical to me. Can you describe what the album, artist & album-artist tags look like for a sample song from two albums which should just be one album?

**Comment by Pixelguin** [comment]
Sorry for the confusion: what you called "Step 2" was the expected result.

Two songs that have this phenomenon occur have matching album tags, mismatched artist tags, and no album-artist tags.

**Comment by timusus** [comment]
OK. So the problem is your songs have mismatched artist tags, which means the Android `MediaScanner`/`MediaStore` thinks they are from different artists (which makes sense), so it then assumes these are two separate albums.

**Comment by Pixelguin** [comment]
That sounds about right. I guess the only difference between now and before is how albums are arranged on the Albums tab - before, the artist tag didn't seem to affect grouping.

**Comment by timusus** [comment]
For as long as I have worked with the`MediaStore`, it has required that both the album _and_ artist tags match for two songs to be considered part of the same album.

It sounds like you've had a different result in the past, but I can't explain that. If it didn't work this way, 'Greatest Hits' by Korn would be merged with 'Greatest Hits' by Queen, which wouldn't make much sense.

**Comment by Pixelguin** [comment]
¯\_(ツ)_/¯

Regardless, my issue is entirely my problem and easily fixed. Thanks again!
