### ISSUE TITLE
Reorder the default app shortcuts order to better match w/ Google's approach

### ISSUE THREAD

**Issue by technacity** [timusus/Shuttle#74]
In first-party Google apps, app shortcuts are arranged with the most important closest to the app icon [ex: when app shortcut list opens above app icon, most important is right above. In Gmail, compose button is closest to icon].

In Shuttle+ on a Pixel running Android 7.1.2, play shortcut is furthest away from the icon, with folder browser closest.

Minor, but wonder if Shuttle's behavior can be updated to match? Thanks.

**Comment by timusus** [comment]
Resolved with 3f763f2b6f1ad8201d0e9b4644cc22bd244b7ac0
