### ISSUE TITLE
Notification artwork expand/collapse animation

### ISSUE THREAD

**Issue by balzabalza** [timusus/Shuttle#78]
Hi everybody,

I don't know if this is a bug or actually a feature request.

I'm running Android Nougat on my nexus 5x. The notification is not respecting the smooth animations that some players (Google Play Music, SoundCloud) have introduced with Android Nougat.

What I'm referring to is the animation you can play in this link:
https://goo.gl/photos/apVXBBGrwS84JnuZ8

Unfortunately, I'm not a developer so I don't know where to put my hands on, but animations like those could contribute to make Shuttle even more eye-candy and refined to many people.

Hope I did not make mistakes in posting this ☺️

**Comment by geecko86** [comment]
@balzabalza Your link doesn't work for me, it says the album is empty.

**Comment by balzabalza** [comment]
https://goo.gl/photos/7S522nijTecNJyxKA

You were right, I deleted it.
