### ISSUE TITLE
Consider releasing under a less restrictive license. 

### ISSUE THREAD

**Issue by carlospaulino** [timusus/Shuttle#8]

**Comment by timusus** [comment]
I put a lot of consideration into the choice of license before publishing the source.

Reasons for choosing GPL:

- I like that GPL means people who clone the app or use the source in their own app need to make their app GPL as well. So it makes the open-sourceness contagious.

- I also don't really want to see a bunch of apps just popping up on the Play Store under a different name, and I feel like GPL discourages that kind of thing.

If you've got some reasons why you think GPLv3 is overly restrictive, I'd be glad to hear them.

**Comment by rosenpin** [comment]
GPL v3 sounds like the perfect choice for this kind of app.
From my experience, open sourcing such a wildly used app will inevitably lead to clones popping up in the Play Store.
GPL v3 somewhat protects you from this, at least you will have a legitimate reason to contact the Google Play developers support once this does happen.

You should probably also add a restriction in addition to the GPL v3, forbidding redistribution of the software without a specified amount of modifications.

You chose a very brave path and I'm sure many developers (including me) will be happy with your decision in the end of the day.
But just from my experience (might not be relevant in your case) this can end up really frustrating.

Good luck!

**Comment by carlospaulino** [comment]
Just imagine how hard it would have been for you to keep the app closed source and monetize it effectively, if the plethora of open source libraries you used were under GPL v3. 

My thoughts on why you should choose as more permissive license pretty much align with this article: https://arstechnica.com/uncategorized/2007/11/why-google-chose-the-apache-software-license-over-gplv2/

Ultimately is your call, and no matter your decision I wish you success.

**Comment by Ivoz** [comment]
If those libraries were under the general appropriate license for them, the LGPL, then it really shouldn't be that hard at all.

If someone specifically wants contagious copyleft for their license, then [L]GPL is perfect. Needs of others who would like to use the project in their business without worrying about "oh noes the gee pee ell!" from their lawyers, come secondary.

**Comment by timusus** [comment]
@carlospaulino monetization was never the source of motivation for Shuttle development - if GPLv3 had been a requirement for the codebase from the outset, I probably would've already had a bunch of contributions by now, and the app would be better for it.

However, my opinion is that if the app is good enough / popular enough, it'll sell. I don't think it makes much difference whether it's open source or not. 

I read the article you posted - it's not clear to me how you think that applies here?

**Comment by faho** [comment]
>You should probably also add a restriction in addition to the GPL v3, forbidding redistribution of the software without a specified amount of modifications.

Please _do not_ effectively create your own license. That just makes it harder for everyone to understand (when I say GPLv3, anyone that has understood it once now knows everything about it). Also, that specific restriction would likely be understood as non-free and therefore preclude distribution on F-Droid - #28.

**Comment by rosenpin** [comment]
GPLv3 doesn't restrict other people from redistributing your software.

> I also don't really want to see a bunch of apps just popping up on the Play Store under a different name, and I feel like GPL discourages that kind of thing.

**Comment by timusus** [comment]
@rosenpin right, but by requiring those distributions to be licensed under GPL, I feel like low effort copies are somewhat discouraged. 

I don't plan to make any modifications to the license at this stage. 

I don't see any compelling reason to change the license.
