### ISSUE TITLE
hi ive been struggling 

### ISSUE THREAD

**Issue by Dirkstaal** [timusus/Shuttle#81]
Importing into android studio takes forever and then i get problems with git and amazonPaid release ect also almost all the laytouts is constraint layouts (only working on android studio 2+) 
But i preffer older studios 

Can you please make an branch with minimal stuff like only the debug apk and release apk no in app purchaces ect so that its a basic project please ?

**Comment by deletescape** [comment]
Are you actually serious about this?

**Comment by timusus** [comment]
@Dirkstaal 

>Importing into android studio takes forever

It may be that your dependencies are out of date. In any case, this is a problem at your end, I can't 'fix' this for you.

> i get problems with git

You'll need to be more specific

> and amazonPaid release 

This is covered in the 'getting started' section of the [Contributing](https://github.com/timusus/Shuttle/blob/dev/.github/CONTRIBUTING.md) document.

>also almost all the laytouts is constraint layouts (only working on android studio 2+)

IIRC constraint layout is used for the now-playing screen, which is one of about one hundred layouts. 

>But i preffer older studios

If your preferences are making it difficult to compile the project, you should consider changing your preferences, or changing the code yourself to make it compatible with deprecated software.

> Can you please make an branch with minimal stuff like only the debug apk and release apk no in app purchaces ect so that its a basic project please ?

No.

The `dev` branch will give you access to the debug apk with no IAPs. Releases are available here: https://github.com/timusus/Shuttle/releases. Building the release APK is not something made available to contributors.
