### ISSUE TITLE
use all the space for covers without cropping

### ISSUE THREAD

**Issue by frumpymoons** [timusus/Shuttle#9]
Hey there,

all my covers have a 1:1 resolution (500x500, 600x600 etc.).
Would it be possible to make the bar with the media buttons smaller, so no cropping is necessary?

My phone is a HTC One M8.

**Comment by timusus** [comment]
Not really. There are too many vast and varied screen sizes - it's not practical to force all other UI elements to resize, to fit one element as a square. On some devices, the buttons would become so small as to be unusable - and it's near impossible to write code which ensures this doesn't happen.

I'm going to close this one, as I really do think the current options are the best options available.
