### ISSUE TITLE
Error launching activity

### ISSUE THREAD

**Issue by IanUme** [timusus/Shuttle#93]
Cloning the repository and checking out dev branch and setting the flavor to devBuild, I get an Error type 3 while trying to build the app.

Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.simplecity.amp_library/.ui.activities.MainActivity }
Error type 3
Error: Activity class {com.simplecity.amp_library/com.simplecity.amp_library.ui.activities.MainActivity} does not exist.

Android studio 2.3.1. I have cleared the build files, deleted the gradle files, and resync'd gradle and it did not fix the problem.

**Comment by IanUme** [comment]
It looks like an Android Studio related bug as it occurred on other cloned repositories, too.

**Comment by timusus** [comment]
Hmm.. It sounds like the 'Run/Debug Configurations' might be attempting to launch the wrong activity?

Make sure the dropdown says 'app'. Then, click on it and go to 'edit configurations'
![screen shot 2017-04-19 at 9 05 59 pm](https://cloud.githubusercontent.com/assets/4422616/25177112/0e2d1544-2544-11e7-8cc2-f26bced2d9e6.png)

It should look like this:
<img width="592" alt="screen shot 2017-04-19 at 9 06 50 pm" src="https://cloud.githubusercontent.com/assets/4422616/25177139/292078e6-2544-11e7-975b-8517edbf0a18.png">
Particularly, the 'launch options' launch should be set to 'default activity'.

If that's all setup right, Maybe just clean the project and sync gradle, and try again.

I'm gonna close this one, based on your comments above.
