### ISSUE TITLE
Error while importing project into android studio

### ISSUE THREAD

**Issue by sdianurag** [timusus/Shuttle#94]
Hello sir, 

while importing this project into android studio i got an error. I don't know how to solve this.

please help... Error is appear in message

**Error:org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'git''
Error:Execution failed for task ':app:fabricGenerateResourcesAmazonFreeRelease'.
Crashlytics Developer Tools error.**

**Comment by timusus** [comment]
Please make sure your build variant is set to `devDebug`. It sounds like currently it's on `amazonFree`.

For more info, see the [Contributing](https://github.com/timusus/Shuttle/blob/dev/.github/CONTRIBUTING.md) document.
