### ISSUE TITLE
[Bug] Popup after selecting ringtone displays wrong text

### ISSUE THREAD

**Issue by balzabalza** [timusus/Shuttle#97]
**Shuttle version:**
 
 v1.6.6
 
**Device, OS:**
 
Android 7.1.2, Nexus 5x

**Description of bug:**
 
After I select a ringtone, a popup telling me that I changed ringtone appears. Good. But text inside it is not correct: in **Italian language** (I'm not sure if this happens for other languages, too), there are some inverted commas at the beginning, but they're missing their "sisters", let me say.

Moreover, there's no spacing between the selected song and the following text. I provide a screenshot for this, as it's more self-explanatory.

![screenshot_20170424-181244](https://cloud.githubusercontent.com/assets/26390194/25473649/9168961c-2b30-11e7-943c-3e40f6bab0eb.png)

 
**Steps to reproduce:**
 
 1. Step 1 Select a song as a ringtone, in Italian language (I don't know if this occurs with any language)
 2. Step 2 See the popup message
 
**Expected outcome:**

If I choose Chanel as a ringtone:

**What's currently displayed**: _"Chanelimpostata come suoneria._
**What I should expect**: _"Chanel" impostata come suoneria._

There are some inverted commas missing after the song, as well as spacing between the song and the following word (in italian: _impostata_)
 
**Observations/Actual Result:**
 
 Check if this is related to the italian translation, or it's a more general thing.

Cheers.

**Comment by timusus** [comment]
Thanks, this has been fixed in the translation system.
